<?php $this->placeholder('headling_1')->captureStart(); ?>
<?php
//echo $this->partial(
//    '_headling_button.phtml', array('title' => $this->translate( 'Add shopOrder' ), 'url' => $this->url(array(), 'shopOrder_admin_new')));
//?>

    <h1><?php echo $this->placeholder('headling_1_content'); ?></h1>
<?php $this->placeholder('headling_1')->captureEnd(); ?>

<?php $this->placeholder('aside')->captureStart(); ?>
<?php echo $this->filter; ?>
<script type="text/javascript">
    $(document).ready(function(){
        changeFilterSelect('select-is-read-filter');
    });

</script>
<?php $this->placeholder('aside')->captureEnd(); ?>

<?php $this->placeholder('toolbar')->captureStart(); ?>
<?php echo $this->render('admin/pagination.phtml'); ?>
<?php $this->placeholder('toolbar')->captureEnd(); ?>

<form id="grid-action-form" method="post" action="">
    <div class="toolbar toolbar-top"><?php echo $this->placeholder('toolbar'); ?></div>
    <table cellspacing="0" cellpadding="0" class="grid datas">
        <tbody>
        <tr>
            <th class="head first">
                <?php echo $this->translate('Id'); ?>
            </th>
            <?php if ( $this->checkToShowStandName ) : ?>
            <th class="head">
                <?php echo $this->translate('label_admin_shop_order-stand-name'); ?>
            </th>
            <?php endif; ?>
            <th class="head">
                <?php echo $this->translate('Created at'); ?>
            </th>
            <th class="head">
                <?php echo $this->translate('label_admin_shop_order-nr'); ?>
            </th>
            <th class="head">
                <?php echo $this->translate('label_admin_shop-last-first-name'); ?>
            </th>
            <th class="head">
                <?php echo $this->translate('label_admin_shop-price-sum'); ?>
            </th>
            <th width="60px" class="head"></th>
        </tr>
        <tr class="row row-template">
            <td valign="top" class="first col"></td>
            <?php if ( $this->checkToShowStandName ) : ?>
                <td valign="top" class="col"></td>
            <?php endif; ?>
            <td valign="top" class="col"></td>
            <td valign="top" class="col"></td>
            <td valign="top" class="col"></td>
            <td valign="top" class="col"></td>
            <td valign="top" class="col"></td>
        </tr>

        <?php foreach( $this->shopOrderList as $key => $shopOrder ): /* @var $shopOrder ShopOrder */ ?>
            <tr class="row <?php if( 0 == ($key%2) ): ?>odd<?php else: ?>even<?php endif; ?> <?php if ( false === $shopOrder->getIsRead() ) : ?> no-read <?php endif; ?>">
                <td valign="top" class="col">
                    <?php echo $shopOrder->getId(); ?>
                </td>
                <?php if ( $this->checkToShowStandName ) : ?>
                    <td valign="top" class="col"><?php echo $shopOrder->ExhibStand->getName(); ?></td>
                <?php endif; ?>
                <td valign="top" class="col"><?php echo date( 'Y-m-d H:i', strtotime( $shopOrder->created_at ) ); ?></td>
                <td valign="top" class="col">
                    <a href="<?php echo $this->url(array('hash' => $shopOrder->getHash()), 'shop_admin_show') ?>">
                        <?php echo $this->translate('label_admin_shop_order-nonr') . ' #' . $shopOrder->getId(); ?>
                    </a>
                </td>
                <td valign="top" class="col">
                    <?php echo $shopOrder->User->getName(); ?>
                </td>
                <td valign="top" class="col">
                    <?php echo $this->currency($shopOrder->getPrice()); ?>
                </td>
                <td valign="top" class="col">
                    <ul class="actions">
                        <li>
                            <a href="<?php echo $this->url(array('hash' => $shopOrder->getHash()), 'shop_admin_show') ?>">
                                <span class="ui-icon ui-icon-document"></span>
                            </a>
                        </li>
                        <li>
                            <a onclick="return confirm('<?php echo $this->translate('Are you sure you want to delete this item?'); ?>');" title="<?php echo $this->escape( $this->translate('Delete') ); ?>" class="help" href="<?php echo $this->url( array( 'hash' => $shopOrder->hash ), 'shop_admin_delete' ); ?>">
                                <span class="ui-icon ui-icon-close"><?php echo $this->escape( $this->translate('Delete') ); ?></span>
                                <span class="bullet" style="width: 36px;"><?php echo $this->escape( $this->translate('Delete') ); ?></span>
                                <span class="ui-icon ui-icon-triangle-1-s queue"></span>
                            </a>
                        </li>
                    </ul>
                </td>
            </tr>
        <?php endforeach; ?>

        </tbody>
    </table>
    <div class="toolbar toolbar-bottom"><?php echo $this->placeholder('toolbar'); ?></div>
</form>

<?php
//function checkToShowStandName() {
//    if ($this->userAuth) {
//        return true;
//    } else {
//        return false;
//    }
//}
//?>
