<?php $this->placeholder('headling_1')->captureStart(); ?>
<?php
echo $this->partial(
	'_headling_button.phtml', array('title' => $this->translate('cms-button_company_add'), 'url' => $this->url(array(), 'company_admin_new')));
?>

<h1><?php echo $this->placeholder('headling_1_content'); ?></h1>
<?php $this->placeholder('headling_1')->captureEnd(); ?>

<?php $this->placeholder('aside')->captureStart(); ?>
<?php echo $this->filter; ?>
<script type="text/javascript">
    $(document).ready(function(){
	changeFilterSelect('select-filter');
    });
    
</script>
<?php $this->placeholder('aside')->captureEnd(); ?>

<?php $this->placeholder('toolbar')->captureStart(); ?>
<?php echo $this->render('commponents/pagination.phtml'); ?>
<?php $this->placeholder('toolbar')->captureEnd(); ?>

<form id="grid-action-form" method="post" action="">
    <div class="toolbar toolbar-top"><?php echo $this->placeholder('toolbar'); ?></div>
    <table cellspacing="0" cellpadding="0" class="grid datas">
        <tbody>
            <tr>
                <th width="10" class="head first"></th>
                <th class="head <?php if ($this->orderCol == 'name'): ?>sorting-<?php if ($this->orderDir == 'DESC'): ?>desc<?php else: ?>asc<?php endif; ?><?php endif; ?>">
                    <a href="?order=name <?php if ($this->orderDir == 'DESC'): ?>ASC<?php else: ?>DESC<?php endif; ?>&page=1">
                        <span class="ui-icon"></span><?=$this->translate('cms-table_company_col-name')?>
                    </a>
                </th>
                <th class="head <?php if ($this->orderCol == 'nip'): ?>sorting-<?php if ($this->orderDir == 'DESC'): ?>desc<?php else: ?>asc<?php endif; ?><?php endif; ?>">
                    <a href="?order=nip <?php if ($this->orderDir == 'DESC'): ?>ASC<?php else: ?>DESC<?php endif; ?>&page=1">
                        <span class="ui-icon"></span><?=$this->translate('cms-table_company_col-nip')?>
                    </a>
                </th>
		<th class="head <?php if ($this->orderCol == 'krs'): ?>sorting-<?php if ($this->orderDir == 'DESC'): ?>desc<?php else: ?>asc<?php endif; ?><?php endif; ?>">
                    <a href="?order=krs <?php if ($this->orderDir == 'DESC'): ?>ASC<?php else: ?>DESC<?php endif; ?>&page=1">
                        <span class="ui-icon"></span><?=$this->translate('cms-table_company_col-krs')?>
                    </a>
                </th>
                <th class="head <?php if ($this->orderCol == 'regon'): ?>sorting-<?php if ($this->orderDir == 'DESC'): ?>desc<?php else: ?>asc<?php endif; ?><?php endif; ?>">
                    <a href="?order=regon <?php if ($this->orderDir == 'DESC'): ?>ASC<?php else: ?>DESC<?php endif; ?>&page=1">
                        <span class="ui-icon"></span><?=$this->translate('cms-table_company_col-regon')?>
                    </a>
                </th>
                <th class="head <?php if ($this->orderCol == 'is_active'): ?>sorting-<?php if ($this->orderDir == 'DESC'): ?>desc<?php else: ?>asc<?php endif; ?><?php endif; ?>">
                    <a href="?order=is_active <?php if ($this->orderDir == 'DESC'): ?>ASC<?php else: ?>DESC<?php endif; ?>&page=1">
                        <span class="ui-icon"></span><?=$this->translate('cms-table_company_col-is-active')?>
                    </a>
                </th>
                
		<th width="60px" class="head"></th>
            </tr>
            <tr class="row row-template">
                <td valign="top" class="first col"></td>
                <td valign="top" class="col"></td>
                <td valign="top" class="col"></td>
                <td valign="top" class="col"></td>
                <td valign="top" class="col"></td>
                <td valign="top" class="col"></td>
            </tr>

	    <?php foreach ($this->companiesList as $key => $company): ?>
    	    <tr class="row <?php if (0 == ($key % 2)): ?>odd<?php else: ?>even<?php endif; ?>">
    		<td valign="top" class="col"><input type="checkbox" name="rowId[]" value="1"></td>
    		<td valign="top" class="col">
                    <a href="<?php echo $this->url(array('hash'=>$company->hash),'company_admin_edit');?>">
                    <?php echo $this->escape($company->getName());?>
                       <a>
		<td valign="top" class="col">
    		    <a href="<?php echo $this->url(array('hash' => $company->getHash()), 'company_admin_edit'); ?>" class="status">
    			<?php echo $this->escape($company->getNip()); ?>
    		    </a>
    		</td>
                <td valign="top" class="col">
    		    <?php echo $this->escape($company->krs); ?>
    		</td>
                <td valign="top" class="col">
    		    <?php echo $this->escape($company->regon); ?>
    		</td>
    		<td valign="top" class="col">
			<?php $isActive = (int) $company->is_active; ?>
    		    <a href="<?php echo $this->url(array('hash' => $company->getHash()), 'company_admin_status'); ?>" class="status">
    			<span class="switch-<?php echo $isActive; ?>"><?php echo $isActive; ?></span>
    		    </a>
    		</td>
    		<td valign="top" class="col">
    		    <ul class="actions">
                    <li>
                        <a title="<?php echo $this->translate('label_edit'); ?>" class="help" href="<?php echo $this->url(array('hash' => $company->getHash()), 'company_admin_edit'); ?>">
                            <span class="ui-icon ui-icon-pencil"><?php echo $this->translate('label_edit'); ?></span>
                            <span class="bullet" style="width: 24px;"><?php echo $this->translate('label_edit'); ?></span>
                            <span class="ui-icon ui-icon-triangle-1-s queue"></span>
                        </a>
                    </li>
                    <li>
                        <a onclick="return confirm('<?php echo $this->translate('cms-label_confirm-delete-item'); ?>');" title="<?php echo $this->translate('label_delete'); ?>" class="help" href="<?php echo $this->url(array('hash' => $company->getHash()), 'company_admin_delete'); ?>">
                            <span class="ui-icon ui-icon-close"><?php echo $this->translate('label_delete'); ?></span>
                            <span class="bullet" style="width: 36px;"><?php echo $this->translate('label_delete'); ?></span>
                            <span class="ui-icon ui-icon-triangle-1-s queue"></span>
                        </a>
                    </li>
    		    </ul>
    		</td>
    	    </tr>
	    <?php endforeach; ?>

        </tbody>
    </table>
    <div class="toolbar toolbar-bottom"><?php echo $this->placeholder('toolbar'); ?></div>
</form>