
<?php $this->headScript()->appendFile('/_js/jquery-1.7.2.min.js'); ?>
<?php $this->headScript()->appendFile('/_externals/jcrop/js/jquery.Jcrop.min.js'); ?>
<?php $this->headLink()->appendStylesheet('/_externals/jcrop/css/jquery.Jcrop.css'); ?>

<style type="text/css">
.imageCroppSave {
	-moz-box-shadow:inset 0px 1px 0px 0px #caefab;
	-webkit-box-shadow:inset 0px 1px 0px 0px #caefab;
	box-shadow:inset 0px 1px 0px 0px #caefab;
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #77d42a), color-stop(1, #5cb811) );
	background:-moz-linear-gradient( center top, #77d42a 5%, #5cb811 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#77d42a', endColorstr='#5cb811');
	background-color:#77d42a;
	-moz-border-radius:6px;
	-webkit-border-radius:6px;
	border-radius:6px;
	border:1px solid #268a16;
	display:inline-block;
	color:#306108;
	font-family:arial;
	font-size:15px;
	font-weight:bold;
	padding:6px 24px;
	text-decoration:none;
	text-shadow:1px 1px 0px #aade7c;
}.imageCroppSave:hover {
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #5cb811), color-stop(1, #77d42a) );
	background:-moz-linear-gradient( center top, #5cb811 5%, #77d42a 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#5cb811', endColorstr='#77d42a');
	background-color:#5cb811;
}.imageCroppSave:active {
	position:relative;
	top:1px;
}
</style>

<style type="text/css">
.imageCroppCancel {
	-moz-box-shadow:inset 0px 1px 0px 0px #f29c93;
	-webkit-box-shadow:inset 0px 1px 0px 0px #f29c93;
	box-shadow:inset 0px 1px 0px 0px #f29c93;
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #fe1a00), color-stop(1, #ce0100) );
	background:-moz-linear-gradient( center top, #fe1a00 5%, #ce0100 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#fe1a00', endColorstr='#ce0100');
	background-color:#fe1a00;
	-moz-border-radius:6px;
	-webkit-border-radius:6px;
	border-radius:6px;
	border:1px solid #d83526;
	display:inline-block;
	color:#ffffff;
	font-family:arial;
	font-size:15px;
	font-weight:bold;
	padding:6px 24px;
	text-decoration:none;
	text-shadow:1px 1px 0px #b23e35;
}.imageCroppCancel:hover {
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #ce0100), color-stop(1, #fe1a00) );
	background:-moz-linear-gradient( center top, #ce0100 5%, #fe1a00 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ce0100', endColorstr='#fe1a00');
	background-color:#ce0100;
}.imageCroppCancel:active {
	position:relative;
	top:1px;
}

</style>

<div>
    <img src="<?php echo $this->ModifiedDate($this->imagePath); ?>" id="target" />
</div>
<div style="text-align: center; padding:20px;">
    <a style="margin-right:10px;" href="javascript:;" class="imageCroppCancel"><?php echo $this->escape($this->translate('cropper_cancel')); ?></a> 
    <a href="javascript:;" class="imageCroppSave" ><?php echo $this->escape($this->translate('cropper_save')); ?></a>
</div>
<script type="text/javascript">

jQuery(function($) {
    
    var currentCords = null
        ,changeCords = null
        ,selection = <?php echo Zend_Json::encode(array_filter($this->selection)).PHP_EOL; ?>
        ,config = <?php echo Zend_Json::encode(array_filter($this->imageParams)).PHP_EOL; ?>
    ;

    changeCords = function(c) {
        currentCords = $.extend({}, c);
    };

    config = $.extend(config, {
        onChange: changeCords
        ,onSelect: changeCords
        ,setSelect: selection
        ,boxWidth: 650
        , boxHeight: 450
    });

    $('#target').Jcrop(config);
    
    $('a.imageCroppCancel').click(function(){
        parent.jQuery.fancybox.close();
    });
    $('a.imageCroppSave').click(function(){
        if(null !== currentCords) {
            parent.jQuery.fancybox.showLoading();
            $.getJSON('', {"cords": currentCords, "config": config}, function(json) {
                parent.jQuery.fancybox.hideLoading();
                if(json.status === 1) {
                    parent.jQuery.fancybox.close();
                } else {
                    alert(json.message);
                }
            });
        } else {
            alert('Select crop area');
        }
    });
});

</script>
