<?php $this->placeholder('h1')->captureStart(); ?>
    <h1><?php echo $this->escape( $this->translate( 'label_default_auth_send_password-recovery' ) ); ?></h1>
<?php $this->placeholder('h1')->captureEnd(); ?>

    <div class="standard_content">
        <p style="padding: 20px;">
            <?php echo $this->translate( 'label_default_auth_send_comm1' );?>
            <?php echo $this->translate( 'label_default_auth_send_comm2' );?>
            <a href="<?php echo $this->url(array(),'home');?>"><?php echo $this->translate('label_default_auth_send_back-to-homepage');?></a>
        </p>
    </div>