
<?php $this->placeholder('headling_1')->captureStart(); ?>
    <?php
    echo $this->partial(
        '_headling_button.phtml', array('title' => $this->translate('Add site'), 'url' => $this->url( array( 'hash' => $this->event->hash ), 'event_admin-site_new')));
    ?>

    <h1><?php echo $this->placeholder('headling_1_content'); ?></h1>
<?php $this->placeholder('headling_1')->captureEnd(); ?>

<?php $this->placeholder('aside')->captureStart(); ?>
    <?php echo $this->filter; ?>
<?php $this->placeholder('aside')->captureEnd(); ?>

<form id="grid-action-form" method="post" action="">
    <table cellspacing="0" cellpadding="0" class="grid datas">
        <tbody>
            <tr>
                <th class="head">
                     <?php echo $this->translate('Title'); ?>
                </th>
                <th width="80px" class="head">
                    <?php echo $this->translate('Visible'); ?>
                </th>
                <th width="60px" class="head"></th>
            </tr>
            <tr class="row row-template">
                <td valign="top" class="first col"></td>
                <td valign="top" class="col"></td>
                <td valign="top" class="col"></td>
                <td valign="top" class="col"></td>
            </tr>

            <?php foreach ($this->eventSiteList as $key => $eventSite ): ?>
                <tr class="row <?php if (0 == ($key % 2)): ?>odd<?php else: ?>even<?php endif; ?>">
                   <td valign="top" class="col">
                        <a href="<?php echo $this->url(array(
                            'hash'=> $eventSite->getHash()
                        ),
                                'event_admin-site_edit'
                                );?>">  <?php echo $this->escape( $eventSite->getTitle() ); ?></a>
                        <?php if( false === $eventSite->languageExists( $this->selectedLanguage ) ): ?>
                            <a href="#" title="<?php echo $this->translate('No translation'); ?>">[!]</a>
                        <?php endif; ?>
                    </td>
                    <td valign="top" class="col">
                        <a href="<?php echo $this->url( array( 'hash' => $eventSite->getHash() ), 'event_admin-site_status' ); ?>" class="status">
                            <span class="switch-<?php echo (int)$eventSite->isActive(); ?>"><?php echo (int)$eventSite->isActive(); ?></span>
                        </a>
                    </td>
                    <td valign="top" class="col">
                        <ul class="actions">
                            <li>
                                <a title="<?php echo $this->translate('Edit'); ?>" class="help" href="<?php echo $this->url(array( 'hash' => $eventSite->getHash() ), 'event_admin-site_edit'); ?>">
                                <span class="ui-icon ui-icon-pencil"><?php echo $this->translate('Edit'); ?></span>
                                <span class="bullet" style="width: 24px;"><?php echo $this->translate('Edit'); ?></span>
                                <span class="ui-icon ui-icon-triangle-1-s queue"></span>
                                </a>
                            </li>
                            <li>
                                <a onclick="return confirm('<?php echo $this->translate('Are you sure you want to delete this item?'); ?>');" title="<?php echo $this->translate('Delete'); ?>" class="help" href="<?php echo $this->url(array( 'hash' => $eventSite->getHash() ), 'event_admin-site_delete'); ?>">
                                <span class="ui-icon ui-icon-close"><?php echo $this->translate('Delete'); ?></span>
                                <span class="bullet" style="width: 36px;"><?php echo $this->translate('Delete'); ?></span>
                                <span class="ui-icon ui-icon-triangle-1-s queue"></span>
                                </a>
                            </li>
                        </ul>
                    </td>
                </tr>
            <?php endforeach; ?>

        </tbody>
    </table>
</form>