<div id="links">
    <div class="floatL left_footer">

        <p>
            <?php echo $this->translate('menu_footer_left');?>
        </p>
    </div>
    <div class="floatR right_footer">
        <p>
            <?=date('Y')?>
                        <?php /*echo $this->translate('menu_footer_right');*/ ?>
            <a href="http://webexpo.pl" title="link_footer_voxcommerce" target="_blank">
                webexpo.pl             
            </a>
        </p>
    </div>
</div>
<div class="clr"></div>
