<!-- <div class="eu-logo">
    <img style="margin-left: auto; margin-right: auto;"src="/_images/frontend/eu_footer.png">
</div> -->
<div id="links">
    <div class="floatL left_footer">
        <a href="<?php echo $this->url(['event_uri' => $this->selectedEvent->getUri(), 'site_uri' => 'regulamin'], 'event_site'); ?>">
            <span><?php echo $this->translate('label_regulations'); ?></span>
        </a>
        <!-- <p>
            <//?php echo $this->translate('menu_footer_left');?>
        </p> -->
    </div>
    <!-- <div class="floatR right_footer">
        <p>
            <//?=date('Y')?>
                        <//?php /*echo $this->translate('menu_footer_right');*/ ?>
            <a href="http://webexpo.pl" title="link_footer_voxcommerce" target="_blank">
                webexpo.pl             
            </a>
        </p>
    </div> -->
</div>
<div class="clr"></div>

