<div class="partnersSlider">
	<a href="javascript:;" onclick="prevSlide();" class="prev"></a>
	<div class="partnersSliderIns">
		
        
        
        <ul class="partnersSliderWrapper">
            <li class="partnerItem">
                <div class="logo firstElem">
                    <a href="http://www.zumi.pl" target="_blank" title="Odwiedź Zumi">
                        <img class="animOp" src="/_images/frontend/default/image_test/zumi.jpg" alt="Zumi" />
                    </a>
                </div>
            </li>
            <li class="partnerItem">
                <div class="logo">
                    <a href="http://www.onet.pl" target="_blank" title="Odwiedź Onet">
                        <img class="animOp" src="/_images/frontend/default/image_test/onet.jpg" alt="Onet" />
                    </a>
                </div>
                <p>Partner</p>
            </li>
            <li class="partnerItem">
                <div class="logo firstElem">
                    <a href="http://www.budimex.pl" target="_blank" title="Odwiedź Budimex">
                        <img class="animOp" src="/_images/frontend/default/image_test/budimex.jpg" alt="Budimex" />
                    </a>
                </div>
                <p>Partner</p>
            </li>
            <li class="partnerItem">
                <div class="logo">
                    <a href="http://www.zumi.pl" target="_blank" title="Odwiedź Zumi">
                        <img class="animOp" src="/_images/frontend/default/image_test/zumi.jpg" alt="Zumi" />
                    </a>
                </div>
            </li>
            <li class="partnerItem">
                <div class="logo">
                    <a href="http://www.onet.pl" target="_blank" title="Odwiedź Onet">
                        <img class="animOp" src="/_images/frontend/default/image_test/onet.jpg" alt="Onet" />
                    </a>
                </div>
                <p>Partner</p>
            </li>
            <li class="partnerItem">
                <div class="logo firstElem">
                    <a href="http://www.budimex.pl" target="_blank" title="Odwiedź Budimex">
                        <img class="animOp" src="/_images/frontend/default/image_test/budimex.jpg" alt="Budimex" />
                    </a>
                </div>
                <p>Partner</p>
            </li>
            <li class="partnerItem">
                <div class="logo">
                    <a href="http://www.zumi.pl" target="_blank" title="Odwiedź Zumi">
                        <img class="animOp" src="/_images/frontend/default/image_test/zumi.jpg" alt="Zumi" />
                    </a>
                </div>
            </li>
            <li class="partnerItem">
                <div class="logo">
                    <a href="http://www.onet.pl" target="_blank" title="Odwiedź Onet">
                        <img class="animOp" src="/_images/frontend/default/image_test/onet.jpg" alt="Onet" />
                    </a>
                </div>
                <p>Partner</p>
            </li>
            <li class="partnerItem">
                <div class="logo firstElem">
                    <a href="http://www.budimex.pl" target="_blank" title="Odwiedź Budimex">
                        <img class="animOp" src="/_images/frontend/default/image_test/budimex.jpg" alt="Budimex" />
                    </a>
                </div>
                <p>Partner</p>
            </li>
            <li class="partnerItem">
                <div class="logo">
                    <a href="http://www.zumi.pl" target="_blank" title="Odwiedź Zumi">
                        <img class="animOp" src="/_images/frontend/default/image_test/zumi.jpg" alt="Zumi" />
                    </a>
                </div>
            </li>
            <li class="partnerItem">
                <div class="logo">
                    <a href="http://www.onet.pl" target="_blank" title="Odwiedź Onet">
                        <img class="animOp" src="/_images/frontend/default/image_test/onet.jpg" alt="Onet" />
                    </a>
                </div>
                <p>Partner</p>
            </li>
            <li class="partnerItem">
                <div class="logo firstElem">
                    <a href="http://www.budimex.pl" target="_blank" title="Odwiedź Budimex">
                        <img class="animOp" src="/_images/frontend/default/image_test/budimex.jpg" alt="Budimex" />
                    </a>
                </div>
                <p>Partner</p>
            </li>
            <li class="partnerItem">
                <div class="logo">
                    <a href="http://www.zumi.pl" target="_blank" title="Odwiedź Zumi">
                        <img class="animOp" src="/_images/frontend/default/image_test/zumi.jpg" alt="Zumi" />
                    </a>
                </div>
            </li>
            <li class="partnerItem">
                <div class="logo">
                    <a href="http://www.onet.pl" target="_blank" title="Odwiedź Onet">
                        <img class="animOp" src="/_images/frontend/default/image_test/onet.jpg" alt="Onet" />
                    </a>
                </div>
                <p>Partner</p>
            </li>
            <li class="partnerItem">
                <div class="logo firstElem">
                    <a href="http://www.budimex.pl" target="_blank" title="Odwiedź Budimex">
                        <img class="animOp" src="/_images/frontend/default/image_test/budimex.jpg" alt="Budimex" />
                    </a>
                </div>
                <p>Partner</p>
            </li>
        </ul>

	</div>
	<a href="javascript:;" onclick="nextSlide();" class="next"></a>
	<div class="clr"></div>
</div>
<div class="clr"></div>