<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pl" lang="pl">
<head>
	<meta http-equiv="content-type" content="text/html;charset=utf-8" />
</head>
<body>
	<div style="font-size: 12px; padding: 10px; font-family: Tahoma;">
		<?php echo $this->mail_content; ?>
	</div>
	<div style="border-top: solid 1px #AAAAAA; padding: 10px; margin-top: 30px; background: #EEEEEE; color: #AAAAAA; font-size: 10px; font-family: Tahoma;">
		Wiadomość została wysłana automatycznie. Proszę na nią nie odpowiadać.
	</div>
</body>
</html>