<?php
    $pages = $this->container->findAllBy('is_footer', true);
?>

<?php if( count( $pages ) > 0 ): ?>
    <ul class="<?php echo $this->menu()->getUlClass(); ?>">
        <?php foreach( $pages as $page ): ?>
            <?php $isActive = $page->isActive(false); ?>
            <?php $liClass = $isActive ? ' class="active"' : ''; ?>
            <li <?php echo $liClass; ?>><?php echo $this->menu()->htmlify($page); ?>|&nbsp;&nbsp;</li><?php echo PHP_EOL ?>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>