<?php echo $this->doctype() ?>
<html class="main">
<head>
    <?php $this->headMeta()->setHttpEquiv('Content-Type', 'text/html;charset=utf-8'); ?>
    <link rel="shortcut icon" href="/img/fav.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon.png"/>
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/apple-touch-icon.png"/>
    <link rel="apple-touch-startup-image" href="/apple-touch-icon.png"/>

    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">

    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <link type="image/x-icon" rel="shortcut icon" href="/img/fav.png">
    <link type="image/x-icon" rel="icon" href="/img/fav.png">
    <script type="text/javascript">var cookie_voxexpo = "CookiesPolicyAccepted-VoxExpo";</script>
    <?php $this->headScript()
        ->prependFile('/_js/mccookies.js')
        ->prependFile('/_js/swfobject.js')
        ->prependFile('/_js/forms.js')
        ->prependFile('/_js/jquery/jquery.form-3.18.js')
        ->prependFile('/_js/jquery/jquery.tools.min.js')
        ->prependFile('/_js/jquery/jquery-1.8.1.min.js'); ?>
    <?php $this->headLink()
        ->prependStylesheet('/_css/frontend/default/style.css')
        ->prependStylesheet('/_css/frontend/default/jquery.mCustomScrollbar.css')
        ->prependStylesheet('/_css/frontend/default/overlay_element.css')
        ->prependStylesheet('/_css/frontend/default/lightbox.css')
        ->prependStylesheet('/_css/frontend/default/jquery-ui.theme.min.css')
        ->prependStylesheet('/_css/frontend/default/jquery-ui.min.css')
//        ->prependStylesheet( '/_css/frontend/default/overlay_element.css' )
        ->prependStylesheet('https://fonts.googleapis.com/css?family=Dosis:400,500,600,700&subset=latin,latin-ext'); ?>
    <?php $this->selectedEvent->getStyle() ? $this->headStyle()->appendStyle($this->selectedEvent->getStyle()) : ''; ?>

    <?php echo $this->headTitle(); ?>
    <?php
    preg_match(
        '@<meta name="description" content="(.*?)" >@mu',
        $this->headMeta()->toString(),
        $matches
    );

    if (!empty($matches)) {
        $this->headMeta()->appendName('og:description', $matches[1]);
    }

    preg_match('@<title>(.*?)</title>@mu', $this->headTitle(), $matches);

    if (!empty($matches)) {
        $this->headMeta()->appendName('og:title', $matches[1]);
    }
    ?>
    <?php echo $this->headMeta()->toString() . "\r\n"; ?>
    <?php echo $this->headLink()->toString() . "\r\n"; ?>
    <?php echo $this->headStyle()->toString() . "\r\n"; ?>

    <meta name="viewport" content="width=1260, user-scalable=no"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <script type="text/javascript" src="/_js/modernizr.custom.55919.js"></script>
    <script type="text/javascript" src="/_js/dfp_audience_pixel.js"></script>

    <noscript>
        <img src="https://pubads.g.doubleclick.net/activity;dc_iu=/134579212/DFPAudiencePixel;ord=1;dc_seg=1041282616?"
             width=1 height=1 border=0 />
    </noscript>
    <meta property="og:title" content="Giełda Pracodawcy, Przedsiębiorczości i Technologii">
    <meta property="og:site_name" content="Giełda Pracodawcy, Przedsiębiorczości i Technologii">
    <meta property="og:description" content="Giełda Pracodawcy, Przedsiębiorczości i Technologii">
    <meta property="og:image" content="https://targipracyposl.webexpo.pl/img/logo.png">
    <meta property="og:image:width" content="1920">
    <meta property="og:image:height" content="1080">
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://targipracyposl.webexpo.pl/">
    
</head>
<body>
<?php echo $this->layout()->content ?>
<footer>
    <?php echo $this->placeholder('footer-content') ?>
</footer>
</div>

<?php echo $this->render('_init-overlay.phtml') ?>

<?php $this->headScript()->captureStart(); ?>
function changePage(sel, showElem, hideElems) {
$(sel).bind('click', function(e) {
e.preventDefault();
$('.hallPageBtn a').removeClass('active');
$(this).addClass('active');
$(showElem).show(500);
$(hideElems).hide(500);
});
}

$(document).ready(function(){
changePage('.formBtn', '#Section', '#Edycje,#Poprzednie,#Wspolpraca');
changePage('#EdycjeBtn', '#Edycje', '#Section,#Poprzednie,#Wspolpraca');
changePage('#PoprzednieBtn', '#Poprzednie', '#Section,#Edycje,#Wspolpraca');
changePage('.WspolpracaBtn', '#Wspolpraca', '#Section,#Edycje,#Poprzednie');
<?php if (!$this->showEvent): ?>
    changePage('#WystawcyBtn', '#Section', '#Edycje,#Poprzednie,#Wspolpraca');
<?php endif; ?>
changePage('header .logo', '#Section', '#Wspolpraca,#Edycje,#Poprzednie');

});

<?php echo $this->googleAnalytics; ?>

<?php $this->headScript()->captureEnd(); ?>

<?php echo $this->headScript()->toString() . "\r\n"; ?>
</body>
</html>
