<?=$this->doctype()?>
<html>
<head>
    <?=$this->headTitle()->toString()."\n" ?>
    <!--[if IE]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <!--[if IE 7]>
    <link href="/_css/admin/ie7.css" media="screen" rel="stylesheet" type="text/css" />
    <![endif]-->

    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <script src="/_js/jquery-1.7.2.min.js" type="text/javascript"></script>

   
    <?php $this->headLink()->appendStylesheet( '/_css/frontend/default/style.css' );?>


    <?=$this->headMeta()->toString()."\n" ?>
    <?=$this->headLink()?>
</head>
<!-- ONET_BODYTAG_BEGIN --><body><!-- ONET_BODYTAG_END -->
    

        <section class="<?php echo $this->selectedAction?$this->selectedAction:'';?>">
           
            <section class="">

                <?php echo $this->layout()->content?>
            </section>
            <div class="clr"></div>
        </section>

        <footer>
        </footer>
<?php $this->headScript()->captureStart();?>
    $('.iconCont a').attr("href", "javascript:");
<?php $this->headScript()->captureEnd(); ?>

<?php echo $this->headScript()->toString()."\r\n" ?>
</body> 
</html>