<!DOCTYPE html>
<html lang="en">
    <head>
	 <meta charset="utf-8">
    <title>Image Cropper</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="noindex">
	<?= $this->headLink() ?>
	<?= $this->headScript() ?>
    <style type="text/css">
body{
	margin:0 !important;
}

</style>
</head>
<body class="fixMargin">
    <?php echo $this->layout()->content; ?>
</body>
</html>
