<?php echo $this->doctype() ?>
<html>
<head>
    <?php $this->headMeta()->setHttpEquiv('Content-Type', 'text/html;charset=utf-8'); ?>

    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <?php $this->headLink()
        ->prependStylesheet( '/_css/frontend/default/style.css' )
        ->prependStylesheet( '/_css/frontend/default/lightbox.css' )
        ->prependStylesheet( '/_css/frontend/default/iframe.css' );
    ?>
    <?php
    $this->headScript()
        ->prependFile('/_js/default.js')
        ->prependFile('/_js/scripts.js')
        ->prependFile('/_js/forms.js')
        ->prependFile('/_js/jquery/jquery.form-3.18.js')
        ->prependFile('/_js/jquery.dataTables.min.js')
        ->prependFile('/_js/jquery.dotimeout.js')
        ->prependFile('/_js/jquery/scrollbar/jquery.mCustomScrollbar.js')
        ->prependFile('/_js/jquery/jquery.mousewheel.min.js')
        ->prependFile('/_js/jquery/jquery-ui-1.10.0.custom.min.js')
        ->prependFile('/_js/jquery/jquery.tools.min.js')
        ->prependFile('/_js/jquery/jquery-1.8.1.min.js');
    ?>

    <?php $this->headLink()
        ->prependStylesheet('https://fonts.googleapis.com/css?family=Dosis:400,500,600,700&subset=latin,latin-ext'); ?>
    <?php echo $this->headLink()->toString()."\r\n"; ?>
    <?php echo $this->headStyle()->toString()."\r\n"; ?>
    
    <meta name="viewport" content="width=1260, user-scalable=no" />
    <script type="text/javascript" src="/_js/modernizr.custom.55919.js"></script>
</head>
<!-- ONET_BODYTAG_BEGIN --><body class="iframe-body"><!-- ONET_BODYTAG_END -->
<div id="iframe-form-container">

    <?php echo $this->layout()->content?>
</div>


    <?php $this->headScript()->captureStart(); ?>
    $(document).ready(function(){
        $(".mcsb").mCustomScrollbar('update');
    });
    <?php $this->headScript()->captureEnd(); ?>

    <?php echo $this->headScript()->toString()."\r\n"; ?>
</body>
</html>