<div class="whiteBg">
				<h2>Dlaczego Wirtualne Targi z Zumi?</h2>
				<div class="pictogramsCont clearfix">
					<div class="pictogramItem first">
						<div class="pictogram pHands"></div>
						<div class="pictogramDesc">
							<h3>RELACJE</h3>
							<p>To jedyna możliwość, aby wejść w&nbsp;bezpośrednią relację z&nbsp;Klientem za&nbsp;pośrednictwem Internetu</p>
						</div>
					</div>
					<div class="pictogramItem">
						<div class="pictogram pBulb"></div>
						<div class="pictogramDesc">
							<h3>INNOWACYJNOŚĆ</h3>
							<p>Zadbaj o&nbsp;swój wizerunek i&nbsp;pokaż się jako firma korzystająca z&nbsp;nowoczesnych rozwiązań sprzedaży i&nbsp;promocji</p>
						</div>
					</div>
					<div class="pictogramItem">
						<div class="pictogram pPig"></div>
						<div class="pictogramDesc">
							<h3>EFEKTYWNOŚĆ KOSZTOWA</h3>
							<p>Dotrzyj do&nbsp;większego grona klientów, inwestując mniejsze pieniądze niż&nbsp;na&nbsp;targach stacjonarnych</p>
						</div>
					</div>
				</div>
			</div>
			<div class="blueBg clearfix">
				<h2>Wirtualne Targi to...</h2>
				<ul class="floatL">
					<li>Narzędzie umożliwiające interakcje wystawcy z&nbsp;Użytkownikami</li>
					<li>Dedykowana Platforma sprzedażowa</li>
					<li>Promocja na&nbsp;stronach Onetu oraz&nbsp;Zumi.pl</li>
					<li>Imprezy tematyczne skierowane do&nbsp;konkretnych branż<br /> i&nbsp;konkretnej grupy odbiorców</li>
				</ul>
				<ul class="floatR">
					<li>Do 200 wystawców na jednej edycji</li>
					<li>Dla wszystkich firm indywidualne stoiska<br /> o&nbsp;określonych funkcjach i&nbsp;możliwościach</li>
					<li>Planowany ruch — 100 000 UU</li>
					<li>Czas trwania — 7 dni</li>
				</ul>
			</div>
			<div class="whiteBg">
				<h2>Z nami zyskujesz...</h2>
				<div class="pictogramsMinCont clearfix">
					<div class="pictogramMinItem first">
						<div class="pictogramMin pPeople"></div>
						<div class="pictogramMinDesc">
							<h3>EFEKTYWNY<br /> ZASIĘG</h3>
							<p>Estymowana liczba 100&nbsp;tys.&nbsp;zaangażowanych Użytkowników odwiedzających targi</p>
						</div>
					</div>
					<div class="pictogramMinItem">
						<div class="pictogramMin pMail"></div>
						<div class="pictogramMinDesc">
							<h3>PAKIET<br /> ŚWIADCZEŃ</h3>
							<p>przeznaczony dla&nbsp;Ciebie Pakiet świadczeń promocyjnych: Mailing, Kampania Odsłonowa, strona&nbsp;główna&nbsp;Zumi, Stoisko i boksy reklamowe na&nbsp;hali targów</p>
						</div>
					</div>
					<div class="pictogramMinItem">
						<div class="pictogramMin pCommunication"></div>
						<div class="pictogramMinDesc">
							<h3>WSPARCIE<br /> KOMUNIKACYJNE</h3>
							<p>Największe serwisy online: Onet, Zumi, Facebook</p>
						</div>
					</div>
					<div class="pictogramMinItem">
						<div class="pictogramMin pDiscount"></div>
						<div class="pictogramMinDesc">
							<h3>EFEKTYWNOŚĆ<br /> KOSZTOWA</h3>
							<p>Koszty udziału i&nbsp;dotarcie do&nbsp;potencjalnego klienta zdecydowanie niższe w stosunku kosztów targów&nbsp;tradycyjnych</p>
						</div>
					</div>
					<div class="pictogramMinItem">
						<div class="pictogramMin pChat"></div>
						<div class="pictogramMinDesc">
							<h3>DZIAŁANIA<br /> SPRZEDAŻOWE</h3>
							<p>Bezpośrednia interakcja z&nbsp;użytkownikiem, możliwość prezentacji i&nbsp;sprzedaży Twoich produktów i&nbsp;usług</p>
						</div>
					</div>
				</div>
			</div>