<div class="whiteBg">
				<h2>Sponsoring</h2>
				<p class="titleDesc">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ac purus odio, eu convallis nunc. </p>
				<div class="pictogramsCont clearfix">
					<div class="pictogramItem first">
						<div class="pictogramDesc">
							<h3 class="big">Sponsor Strategiczny</h3>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dostępność miejsc: 1</p>
							<div class="parsList">
								<p>MAILING DO 100 000 UŻYTKOWNIKÓW</p>
								<p>STOISKO W CENTRALNYM MIEJSCU HALI</p>
								<p>OBECNOŚĆ NA MATERIAŁACH<br /> 
								PROMOCJYJNYCH TARGÓW</p>
								<p>200 000 odsłon NAVIBOX<br /> 
								STRONA GŁÓWNA ZUMI</p>
								<p>WYRÓŻNIENIE NA STRONIE<br /> 
								INTERNETOWEJ I HALI TARGÓW</p>
							</div>
						</div>
					</div>
					<div class="pictogramItem">
						<div class="pictogramDesc">
							<h3 class="big">Sponsor Branżowy</h3>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dostępność miejsc: 5</p>
							<div class="parsList">
								<p>WYŁĄCZNOŚĆ BRANŻOWA</p>
								<p>MAILING DO 50 000 UŻYTKOWNIKÓW</p>
								<p>STOISKO W CENTRALNYM MIEJSCU HALI</p>
								<p>100 000 odsłon NAVIBOX<br /> STRONA GŁÓWNA ZUMI</p>
								<p>WYRÓŻNIENIE NA STRONIE<br /> INTERNETOWEJ I HALI TARGÓW</p>
							</div>
						</div>
					</div>
					<div class="pictogramItem">
						<div class="pictogramDesc">
							<h3 class="big">Sponsor Regionalny</h3>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dostępność miejsc: 2 w Województwie</p>
							<div class="parsList">
								<p>STOISKO W CENTRALNYM MIEJSCU HALI</p>
								<p>BOX NA SERWISIE<br /> REGIONALNYM ONET (2dni)</p>
								<p>50 000 odsłon NAVIBOX<br /> STRONA GŁÓWNA ZUMI</p>
							</div>
						</div>
					</div>
				</div>
			</div>