<div class="whiteBg clearfix" style="padding-bottom:0px;">
				<div class="frame floatR"><img src="/_images/frontend/default/stand_example.png" alt="przykładowe stoisko" /></div>
				<h2>Opis stoiska Wirtualnych Targów Zumi</h2>
				<p class="titleDesc">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ac purus odio, eu convallis nunc. Integer condimentum porta erat, vitae ssem. Integer bibendum vestibulum dignissim.</p>
				<p class="titleDesc">Mauris ac purus odio, eu convallis nunc. Integer condimentum porta erat, vitae ssem. Integer bibendum vestibulum dignissim.  Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
			</div>
			<div class="whiteBg clearfix">
				<div class="pictogramsSmallCont clearfix">
					<div class="pictogramSmallItem clearfix firstInLine">
						<div class="pictogramSmall pChat"></div>
						<div class="pictogramSmallDesc">
							<h3>AUTOMATYCZNY LIVE CHAT</h3>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ac purus odio, eu convallis nunc.</p>
						</div>
					</div>
					<div class="pictogramSmallItem clearfix">
						<div class="pictogramSmall pPerson"></div>
						<div class="pictogramSmallDesc">
							<h3>WYBÓR OPIEKUNA STANOWISKA</h3>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ac purus odio, eu convallis nunc. </p>
						</div>
					</div>
					<div class="pictogramSmallItem clearfix firstInLine">
						<div class="pictogramSmall pPersonalize"></div>
						<div class="pictogramSmallDesc">
							<h3>PERSONALIZACJA STOISKA</h3>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ac purus odio, eu convallis nunc.</p>
						</div>
					</div>
					<div class="pictogramSmallItem clearfix">
						<div class="pictogramSmall pMail"></div>
						<div class="pictogramSmallDesc">
							<h3>FORMULARZ KONTAKTOWY</h3>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ac purus odio, eu convallis nunc. </p>
						</div>
					</div>
					<div class="pictogramSmallItem clearfix firstInLine">
						<div class="pictogramSmall pScreen"></div>
						<div class="pictogramSmallDesc">
							<h3>BOKSY WIZUALNE Z OFERTĄ PROMOCYJNĄ<br /> W TYM VIDEO</h3>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ac purus odio, eu convallis nunc.</p>
						</div>
					</div>
					<div class="pictogramSmallItem clearfix">
						<div class="pictogramSmall pSocial"></div>
						<div class="pictogramSmallDesc">
							<h3>INTEGRACJA Z SERWISAMI <br />SPOŁECZNOŚCIOWYMI</h3>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ac purus odio, eu convallis nunc. </p>
						</div>
					</div>
					
				</div>
			</div>