<?php $this->placeholder('headling_1')->captureStart(); ?>
<?php
echo $this->partial(
    '_headling_button.phtml', ['title' => $this->translate('Add new translation'), 'url' => $this->url([], 'admin_translation_new')]);
?>

<h1><?php echo $this->placeholder('headling_1_content'); ?></h1>
<?php $this->placeholder('headling_1')->captureEnd(); ?>


<?php $this->placeholder('aside')->captureStart(); ?>
<?php echo $this->filter; ?>
<?php $this->placeholder('aside')->captureEnd(); ?>

<script type="text/javascript">
    //    $(document).ready(function(){
    //        changeFilterSelect('select-filter');
    //    });
</script>


<?php $this->placeholder('toolbar')->captureStart(); ?>
<?php echo $this->render('admin/pagination.phtml'); ?>
<?php $this->placeholder('toolbar')->captureEnd(); ?>

<form id="grid-action-form" method="post" action="">
    <div class="toolbar toolbar-top"><?php echo $this->placeholder('toolbar'); ?></div>
    <table cellspacing="0" cellpadding="0" class="grid datas">
        <tbody>
        <tr>
            <th class="head first <?php if ($this->orderCol == 'text'): ?>sorting-<?php if ($this->orderDir == 'DESC'): ?>desc<?php else: ?>asc<?php endif; ?><?php endif; ?>">
                <a href="?order=text <?php if ($this->orderDir == 'DESC'): ?>ASC<?php else: ?>DESC<?php endif; ?>&page=1">
                    <span class="ui-icon"></span>
                    <?php echo $this->translate('Translated text'); ?>
                </a>
            </th>
            <th class="head <?php if ($this->orderCol == 'translation'): ?>sorting-<?php if ($this->orderDir == 'DESC'): ?>desc<?php else: ?>asc<?php endif; ?><?php endif; ?>">
                <a href="?order=translation <?php if ($this->orderDir == 'DESC'): ?>ASC<?php else: ?>DESC<?php endif; ?>&page=1">
                    <span class="ui-icon"></span>
                    <?php echo $this->translate('Translation'); ?>
                </a>
            </th>
            <th class="head <?php if ($this->orderCol == 'id_language'): ?>sorting-<?php if ($this->orderDir == 'DESC'): ?>desc<?php else: ?>asc<?php endif; ?><?php endif; ?>">
                <a href="?order=id_language <?php if ($this->orderDir == 'DESC'): ?>ASC<?php else: ?>DESC<?php endif; ?>&page=1">
                    <span class="ui-icon"></span>
                    <?php echo $this->translate('Language'); ?>
                </a>
            </th>
            <th class="head <?php if ($this->orderCol == 'is_active'): ?>sorting-<?php if ($this->orderDir == 'DESC'): ?>desc<?php else: ?>asc<?php endif; ?><?php endif; ?>">
                <a href="?order=is_active <?php if ($this->orderDir == 'DESC'): ?>ASC<?php else: ?>DESC<?php endif; ?>&page=1">
                    <span class="ui-icon"></span>
                    <?php echo $this->translate('Visible'); ?>
                </a>
            </th>
            <th width="60px" class="head"></th>
        </tr>
        <tr class="row row-template">
            <td valign="top" class="first col"></td>
            <td valign="top" class="col"></td>
            <td valign="top" class="col"></td>
            <td valign="top" class="col"></td>
            <td valign="top" class="col"></td>
        </tr>

        <?php foreach ($this->translationsList as $key => $translation): ?>
            <?php if ($translation instanceof Translation): ?>
                <tr class="row <?php if (0 == ($key % 2)): ?>odd<?php else: ?>even<?php endif; ?>">
                    <td valign="top" class="col"><?php echo $this->escape($translation->getText()); ?></td>
                    <td valign="top" class="col">
                        <a class="edit"
                           href="<?php echo $this->url(['hash' => $translation->getHash()], 'admin_translation_edit'); ?>">
                            <?php echo $this->escape($translation->getTranslationText()); ?>
                        </a>
                    </td>
                    <td valign="top" class="col">
                        <a class="edit"
                           href="<?php echo $this->url(['hash' => $translation->getHash()], 'admin_translation_edit'); ?>">
                            <?php echo $this->escape($translation->getLanguage()
                                ? $translation->getLanguage()->getOriginalName() : ''); ?>
                        </a>
                    </td>
                    <td valign="top" class="col">
                        <?php $isActive = (int)$translation->getIsActive() ?>
                        <a href="<?php echo $this->url(['hash' => $translation->getHash()], 'admin_translation_status'); ?>"
                           class="status">
                            <span class="switch-<?php echo $isActive; ?>"><?php echo $isActive; ?></span>
                        </a>
                    </td>
                    <td valign="top" class="col">
                        <ul class="actions">
                            <li>
                                <a title="<?php echo $this->escape($this->translate('Edit')); ?>" class="help"
                                   href="<?php echo $this->url(['hash' => $translation->getHash()], 'admin_translation_edit'); ?>">
                                    <span class="ui-icon ui-icon-pencil"><?php echo $this->escape($this->translate('Edit')); ?></span>
                                    <span class="bullet"
                                          style="width: 24px;"><?php echo $this->escape($this->translate('Edit')); ?></span>
                                    <span class="ui-icon ui-icon-triangle-1-s queue"></span>
                                </a>
                            </li>
                            <li>
                                <a onclick="return confirm('<?php echo $this->translate('Are you sure you want to delete this item?'); ?>');"
                                   title="<?php echo $this->escape($this->translate('Delete')); ?>" class="help"
                                   href="<?php echo $this->url(['hash' => $translation->getHash()], 'admin_translation_delete'); ?>">
                                    <span class="ui-icon ui-icon-close"><?php echo $this->escape($this->translate('Delete')); ?></span>
                                    <span class="bullet"
                                          style="width: 36px;"><?php echo $this->escape($this->translate('Delete')); ?></span>
                                    <span class="ui-icon ui-icon-triangle-1-s queue"></span>
                                </a>
                            </li>
                        </ul>
                    </td>
                </tr>
            <?php endif; ?>
        <?php endforeach; ?>

        </tbody>
    </table>
    <div class="toolbar toolbar-bottom"><?php echo $this->placeholder('toolbar'); ?></div>
</form>
