<script type="text/javascript" src="//www.google.com/jsapi"></script>
<script type="text/javascript" src="<?= $this->BaseUserUri(); ?>/_js/statistics_chart_functions.js"></script>

<script type="text/javascript">
      google.load("visualization", "1", {packages:["imagebarchart", "annotatedtimeline"]});
      google.setOnLoadCallback(showGraphs);
	  function showGraphs() {
              $.getJSON("<?= $this->url(array('type'=>  ExhibStatisticsType::STAND_FILE_DOWNLOAD ,'hash' => $this->exhib_stand->getHash()), 'statistics_admin-history'); ?>?date_from=<?php echo $this->search['date_from'];?>&date_to=<?php echo $this->search['date_to'];?>", statistics_data_handler);
	  }
      
</script>
<?php $this->placeholder('headling_1')->captureStart(); ?>

<h1><?php echo $this->placeholder('headling_1_content'); ?></h1>
<?php $this->placeholder('headling_1')->captureEnd(); ?>
<?php if(!empty($this->exhib_stand)) : ?>
<form id="grid-action-form" method="post" action="">
    <div class="toolbar toolbar-top"><?php echo $this->placeholder('toolbar'); ?></div>
    <table cellspacing="0" cellpadding="0" class="grid datas">
        <tbody>
            <tr>
                <th class="head <?php if ($this->orderCol == 'id_user'): ?>sorting-<?php if ($this->orderDir == 'DESC'): ?>desc<?php else: ?>asc<?php endif; ?><?php endif; ?>">
                    <a href="?order=id_user <?php if ($this->orderDir == 'DESC'): ?>ASC<?php else: ?>DESC<?php endif; ?>&page=1">
                        <span class="ui-icon"></span><?php echo $this->translate('File name'); ?>
                    </a>
                </th>
                <th class="head <?php if ($this->orderCol == 'is_active'): ?>sorting-<?php if ($this->orderDir == 'DESC'): ?>desc<?php else: ?>asc<?php endif; ?><?php endif; ?>">
                    <a href="?order=is_active <?php if ($this->orderDir == 'DESC'): ?>ASC<?php else: ?>DESC<?php endif; ?>&page=1">
                        <span class="ui-icon"></span><?php echo $this->translate('Download count'); ?>
                    </a>
                </th>                
            </tr>
            <tr class="row row-template">
                <td valign="top" class="col"></td>
                <td valign="top" class="col"></td>
            </tr>      
            <?php if(!empty($this->exhib_stand->ExhibStandFile)): ?>
                <?php foreach ($this->exhib_stand->ExhibStandFile as $exhib_stand_file) : ?>
                <tr class="row">
                    <td valign="top" class="col">
                        <?php echo $this->escape($exhib_stand_file->getName()); ?>
                    </td>
                    <td valign="top" class="col">
                        <?= isset($this->statisticsList[$exhib_stand_file->getId()]) ?  $this->escape($this->statisticsList[$exhib_stand_file->getId()]) : 0; ?>
                    </td>
                </tr> 
                <?php endforeach; ?>
            <?php endif; ?>
        </tbody>
    </table>

</form>
<?php endif; ?>
<div id="time_line" style="height: 300px; margin-left: auto; margin-right: auto;">
    &nbsp;
</div>

