<script type="text/javascript" src="//www.google.com/jsapi"></script>
<script type="text/javascript" src="<?= $this->BaseUserUri(); ?>/_js/statistics_chart_functions.js"></script>

<script type="text/javascript">
      google.load("visualization", "1", {packages:["imagebarchart", "annotatedtimeline"]});
      google.setOnLoadCallback(showGraphs);
	  function showGraphs() {
              $.getJSON("<?= $this->url(array('type'=>  'stand_view','hash' => $this->exhib_stand->getHash()), 'statistics_admin-history'); ?>?date_from=<?php echo $this->search['date_from'];?>&date_to=<?php echo $this->search['date_to'];?>", statistics_data_handler);
	  }	        
</script>
<?php $this->placeholder('headling_1')->captureStart(); ?>

<h1><?php echo $this->placeholder('headling_1_content'); ?></h1>
<?php $this->placeholder('headling_1')->captureEnd(); ?>
<?php $this->placeholder('aside')->captureStart(); ?>
<?php echo $this->filter; ?>
<?php $this->placeholder('aside')->captureEnd(); ?>
<?php if(!empty($this->exhib_stand)) : ?>
<h2><?php echo $this->event->getTitle();?> - <?php echo $this->exhib_stand->getName();?></h2>
<div id="time_line" style="height: 300px; margin-left: auto; margin-right: auto;">
    &nbsp;
</div>
<form id="grid-action-form" method="post" action="">
    <div class="toolbar toolbar-top"><?php echo $this->placeholder('toolbar'); ?></div>
    <table cellspacing="0" cellpadding="0" class="grid datas">
        <tbody>
            <tr>
                <th class="head <?php if ($this->orderCol == 'id_user'): ?>sorting-<?php if ($this->orderDir == 'DESC'): ?>desc<?php else: ?>asc<?php endif; ?><?php endif; ?>">
                    <a href="?order=id_user <?php if ($this->orderDir == 'DESC'): ?>ASC<?php else: ?>DESC<?php endif; ?>&page=1">
                        <span class="ui-icon"></span><?php echo $this->translate('Username'); ?>
                    </a>
                </th>
                <th class="head <?php if ($this->orderCol == 'is_active'): ?>sorting-<?php if ($this->orderDir == 'DESC'): ?>desc<?php else: ?>asc<?php endif; ?><?php endif; ?>">
                    <a href="?order=is_active <?php if ($this->orderDir == 'DESC'): ?>ASC<?php else: ?>DESC<?php endif; ?>&page=1">
                        <span class="ui-icon"></span><?php echo $this->translate('Views count'); ?>
                    </a>
                </th>                
            </tr>
            <tr class="row row-template">
                <td valign="top" class="col"></td>
                <td valign="top" class="col"></td>
            </tr>
            <?php if(!empty($this->statisticsList)) : ?>
                <?php foreach ($this->statisticsList as $statistic): ?>
                <tr class="row">
                    <td valign="top" class="col">
                        <?php echo !empty($statistic->User) ? $this->escape($statistic->User->getFirstName()).' '.$this->escape($statistic->User->getLastName() ) : 'No logged in'; ?>
                    </td>
                    <td valign="top" class="col">
                        <?= $statistic->count; ?>
                    </td>
                </tr>             
                <?php endforeach; ?>
            <?php endif; ?>
        </tbody>
    </table>

</form>
<?php endif; ?>


