<?php $this->placeholder('headling_1')->captureStart(); ?>
    <?php
    echo $this->partial(
        '_headling_button.phtml', array('title' => $this->translate('Add new file'), 'url' => $this->url( array( 'hash' => $this->event->getHash() ), 'event_admin-file_new')));
    ?>
    <h1><?php echo $this->placeholder('headling_1_content'); ?></h1>
<?php $this->placeholder('headling_1')->captureEnd(); ?>



<div>
    <table class="grid datas">
        <tr>
            <td style="width: 25%"><b>Wydarzenie: </b></td>
            <td><?php echo $this->escape( $this->event->getTitle() ); ?></td>
        </tr>
<!--        <tr>
            <td>
                <b>Treść dodana do wiadomości e-mail</b>
                <a href="<?php //echo $this->url( array( 'hash' => $this->event->getHash() ), 'event_admin-file_mail-text' ); ?>">
                    <img src="/_images/icon/edit_16.gif" class="mb-3" />
                </a>
            </td>
            <td>
                <?php //echo $this->event->getDownloadMailText(); ?>
            </td>
        </tr>-->
    </table>
</div>
<div class="spacerL"></div>


<table cellspacing="0" cellpadding="0" class="grid datas">
    <tbody>
        <tr>
            <th class="head"><?php echo $this->translate('Title'); ?></th>
            <th class="head"><?php echo $this->translate('Link'); ?></th>
            <th class="head"><?php echo $this->translate('Options'); ?></th>
        </tr>
        <tr class="row row-template">
            <td valign="top" class="first col"></td>
            <td valign="top" class="col"></td>
            <td valign="top" class="col"></td>
        </tr>

        <?php if( $this->eventFileList->count() === 0 ): ?>
            <tr>
                <td colspan="3">
                    <div class="msg-attention">
                            <?php echo $this->translate( 'The list is empty. If you want to add a new item' ); ?>
                            <a href="<?php echo $this->url( array( 'hash' => $this->event->getHash() ), 'event_admin-file_new' ); ?>">
                                <?php echo $this->translate('click here'); ?> &raquo;
                            </a>
                    </div>
                </td>
            </tr>
        <?php else: ?>
             <?php foreach ($this->eventFileList as $key => $eventFile ): ?>
                <tr class="row <?php if (0 == ($key % 2)): ?>odd<?php else: ?>even<?php endif; ?>">
                    <td valign="top" class="col">
                        <a class="edit" href="<?php echo $this->url(array('hash' => $eventFile->getHash()), 'event_admin-file_edit'); ?>">
                            <?php echo $this->escape( $eventFile->getTitle() ); ?>
                        </a>
                    </td>
                    <td valign="top" class="col">
                        <a href="<?php echo $eventFile->getBrowserFile(); ?>" target="_blank">
                            <?php echo $this->translate('pobierz plik');?> &raquo;
                        </a>
                    </td>
                    <td valign="top" class="col">
                        <ul class="actions">
                            <li>
                                <a title="<?php echo $this->translate('Edit'); ?>" class="help" href="<?php echo $this->url(array('hash' => $eventFile->getHash()), 'event_admin-file_edit'); ?>">
                                    <span class="ui-icon ui-icon-pencil"><?php echo $this->translate('Edit'); ?></span>
                                    <span class="bullet" style="width: 24px;"><?php echo $this->translate('Edit'); ?></span>
                                    <span class="ui-icon ui-icon-triangle-1-s queue"></span>
                                </a>
                            </li>
                            <li>
                                <a onclick="return confirm('<?php echo $this->translate('Are you sure you want to delete this item?'); ?>');" title="<?php echo $this->translate('Delete'); ?>" class="help" href="<?php echo $this->url(array('hash' => $eventFile->getHash()), 'event_admin-file_delete'); ?>">
                                    <span class="ui-icon ui-icon-close"><?php echo $this->translate('Delete'); ?></span>
                                    <span class="bullet" style="width: 36px;"><?php echo $this->translate('Delete'); ?></span>
                                    <span class="ui-icon ui-icon-triangle-1-s queue"></span>
                                </a>
                            </li>
                        </ul>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>

    </tbody>
</table>