
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Bootstrap Example</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <style>
            .table th:first-child{
                text-align: left !important;
            }
            .table td{
                text-align:center;
            }
            .table td:first-child{
                text-align: left !important;
            }
            .table td:last-child{
                text-align: center !important;
            }
            .table th{
                text-align: center;
            }
        </style>
    </head>
    <body>
        <?php $this->placeholder('headling_1')->captureStart(); ?>
        <?php
        echo $this->partial(
                '_headling_button.phtml', array('title' => $this->translate('Add invoice'), 'url' => $this->url(array(), 'invoice_admin-new')));
        ?>

        <h1><?php echo $this->placeholder('headling_1_content'); ?></h1>
        <?php $this->placeholder('headling_1')->captureEnd(); ?>

        <table class="table table-hover">
            <thead>
                <tr>
                    <th>L.p.</th>
                    <th>NR</th>
                    <th>Wystawca</th>
                    <th>Cena</th>
                    <th>Termin <br> płatności</th>
                    <th>Status <br> płatności</th>
                    <th>Akcja</th>
                </tr>
            </thead>
            <tbody>
                <?php echo $this->partial('invoice-list.phtml', $this); ?>
            </tbody>
        </table>


    </div>
</body>
</html>


