<?php
$this->headLink()->appendStylesheet('/_css/admin/form.css');
?>
<?php $this->placeholder('headling_1')->captureStart(); ?>
<h1><?php echo $this->placeholder('headling_1_content'); ?></h1>
<?php $this->placeholder('headling_1')->captureEnd(); ?>


<?php echo $this->form; ?>

<script type="text/javascript">
        $(document).ready(function () {
           $('#submit').css('color', 'red');
        });

</script>