<?php $this->placeholder('headling_1')->captureStart(); ?>
<?php if($this->userAuth->hasAccess('event_admin_new')):?>
    <?php echo $this->partial( '_headling_button.phtml',
        array('title' => $this->translate('cms-button_event_add'), 'url' => $this->url(array(), 'admin_event_new'))); ?>
<?php endif; ?>
<h1><?php echo $this->placeholder('headling_1_content'); ?></h1>
<?php $this->placeholder('headling_1')->captureEnd(); ?>

<?php $this->placeholder('aside')->captureStart(); ?>
<?php echo $this->filter; ?>

<script type="text/javascript">
    $(document).ready(function(){
        changeFilterSelect('select-filter');
    });

</script>
<?php $this->placeholder('aside')->captureEnd(); ?>

<?php $this->placeholder('toolbar')->captureStart(); ?>
    <?php echo $this->render('commponents/pagination.phtml'); ?>
<?php $this->placeholder('toolbar')->captureEnd(); ?>

<form id="grid-action-form" method="post" action="">
    <div class="toolbar toolbar-top"><?php echo $this->placeholder('toolbar'); ?></div>
    <table cellspacing="0" cellpadding="0" class="grid datas">
        <tbody>
        <tr>
            <th class="head first <?php if($this->orderCol == 't.title'): ?>sorting-<?php if($this->orderDir == 'DESC'): ?>desc<?php else: ?>asc<?php endif; ?><?php endif; ?>">
                <a href="?order=t.title <?php if($this->orderDir == 'DESC'): ?>ASC<?php else: ?>DESC<?php endif; ?>&page=1">
                    <span class="ui-icon"></span><?php echo $this->translate('cms-table_event_col-title'); ?>
                </a>
            </th>
            <th class="head <?php if($this->orderCol == 'created_at'): ?>sorting-<?php if($this->orderDir == 'DESC'): ?>desc<?php else: ?>asc<?php endif; ?><?php endif; ?>">
                <a href="?order=created_at <?php if($this->orderDir == 'DESC'): ?>ASC<?php else: ?>DESC<?php endif; ?>&page=1">
                    <span class="ui-icon"></span><?php echo $this->translate('cms-table_event_col-cteated-on'); ?>
                </a>
            </th>
            <th class="head <?php if($this->orderCol == 'is_archive'): ?>sorting-<?php if($this->orderDir == 'DESC'): ?>desc<?php else: ?>asc<?php endif; ?><?php endif; ?>">
                <a href="?order=is_archive <?php if($this->orderDir == 'DESC'): ?>ASC<?php else: ?>DESC<?php endif; ?>&page=1">
                    <span class="ui-icon"></span><?php echo $this->translate('cms-table_event_col-is-archive'); ?>
                </a>
            </th>
            <th class="head <?php if($this->orderCol == 'is_active'): ?>sorting-<?php if($this->orderDir == 'DESC'): ?>desc<?php else: ?>asc<?php endif; ?><?php endif; ?>">
                <a href="?order=is_active <?php if($this->orderDir == 'DESC'): ?>ASC<?php else: ?>DESC<?php endif; ?>&page=1">
                    <span class="ui-icon"></span><?php echo $this->translate('cms-table_event_col-is-active'); ?>
                </a>
            </th>
            <th class="head <?php if($this->orderCol == 'is_chat_schedule'): ?>sorting-<?php if($this->orderDir == 'DESC'): ?>desc<?php else: ?>asc<?php endif; ?><?php endif; ?>">
                <a href="?order=is_active <?php if($this->orderDir == 'DESC'): ?>ASC<?php else: ?>DESC<?php endif; ?>&page=1">
                    <span class="ui-icon"></span><?php echo $this->translate('cms-table_event_chat-schedule'); ?>
                </a>
            </th>
            <th width="60px" class="head"></th>
        </tr>
        <tr class="row row-template">
            <td valign="top" class="first col"></td>
            <td valign="top" class="col"></td>
            <td valign="top" class="col"></td>
            <td valign="top" class="col"></td>
            <td valign="top" class="col"></td>
        </tr>

        <?php foreach($this->eventList as $key => $event): /* @var $event Event */ ?>
            <tr class="row <?php if(0 == ($key % 2)): ?>odd<?php else: ?>even<?php endif; ?>">
                <td valign="top" class="col">
                    <a class="edit" href="<?php echo $this->url(array('hash' => $event->getHash()), 'admin_event_edit'); ?>">
                        <?php echo $this->escape($event->getTitle()); ?>
                        <?php if(false === $event->translationExists()): ?>
                            <a href="#" title="<?=$this->translate('label_translation_not_exists')?>">[!]</a>
                        <?php endif; ?>
                    </a>
                </td>
                <td valign="top" class="col"><?php echo date('Y-m-d H:i', strtotime($event->created_at)); ?></td>
                <td valign="top" class="col">
                    <?php $isArchive = (int) $event->is_archive; ?>
                    <a href="<?php echo $this->url(array('hash' => $event->getHash()), 'admin_event_archive'); ?>" class="status">
                        <span class="switch-<?php echo $isArchive; ?>"><?php echo $isArchive; ?></span>
                    </a>
                </td>
                <td valign="top" class="col">
                    <?php $isActive = (int) $event->is_active; ?>
                    <a href="<?php echo $this->url(array('hash' => $event->getHash()), 'admin_event_status'); ?>" class="status">
                        <span class="switch-<?php echo $isActive; ?>"><?php echo $isActive; ?></span>
                    </a>
                </td>
                <td valign="top" class="col">
                    <?php $isChatSchedule = (int) $event->is_chat_schedule; ?>
                    <a href="<?php echo $this->url(array('hash' => $event->getHash()), 'admin_event_is-chat-schedule'); ?>" class="status">
                        <span class="switch-<?php echo $isChatSchedule; ?>"><?php echo $isChatSchedule; ?></span>
                    </a>
                </td>
                <td valign="top" class="col">
                    <ul class="actions">
                        <li>
                            <a title="<?php echo $this->translate('label_edit'); ?>" class="help" href="<?php echo $this->url(array('hash' => $event->getHash()), 'admin_event_edit'); ?>">
                                <span class="ui-icon ui-icon-pencil"><?php echo $this->translate('label_edit'); ?></span>
                                <span class="bullet" style="width: 24px;"><?php echo $this->translate('label_edit'); ?></span>
                                <span class="ui-icon ui-icon-triangle-1-s queue"></span>
                            </a>
                        </li>
                        <li>
                            <a onclick="return confirm('<?php echo $this->translate('cms-label_confirm-delete-item'); ?>');" title="<?php echo $this->translate('label_delete'); ?>" class="help" href="<?php echo $this->url(array('hash' => $event->getHash()), 'admin_event_delete'); ?>">
                                <span class="ui-icon ui-icon-close"><?php echo $this->translate('label_delete'); ?></span>
                                <span class="bullet" style="width: 36px;"><?php echo $this->translate('label_delete'); ?></span>
                                <span class="ui-icon ui-icon-triangle-1-s queue"></span>
                            </a>
                        </li>
                    </ul>
                </td>
            </tr>
        <?php endforeach; ?>

        </tbody>
    </table>
    <div class="toolbar toolbar-bottom"><?php echo $this->placeholder('toolbar'); ?></div>
</form>