<?php $this->headLink()->appendStylesheet('/_css/admin/form.css'); ?>

<?php if ($this->event): ?>
<h1><?php echo $this->translate('Patroni medialni'); ?></h1>

    <?php echo $this->eventPatronsForm; ?>
<?php else: ?>
    <h1><?php echo $this->translate('no_event_selected'); ?></h1>
<?php endif; ?>

<script>
<?php $this->headScript()->captureStart(); ?>

    $(function() {
        $('body').on('click', ".mediaPatronsAddBanner", mediaPatronsAddBanner);
        $('body').on('click', ".hideShowGroup", hideShowGroup);
        $('form#EventFormAdminMediaPatronsForm').sortable({
            items: '> .sortPatrons'
        });
    });

    var mediaPatronsAddBanner = function (){
        var _this = $(this);
        var value = _this.html();

        $.ajax({
            url:'<?=$this->url(array(), 'event_admin_patrons_get-banner')?>'
            ,type: 'post'
            ,dataType: 'json'
            ,beforeSend:function(){
                _this.html('<?=$this->translate('label_loading_please_wait')?>');
            }
            ,success: function(data){
                _this.html(value);
                $('#mediaPatronsAddBanner').append(data.html);
            }
        });

        return false;
    }

    var hideShowGroup = function (){

        $('.sortPatrons').each(function() {
            var _elem = $(this).children('.form-item')
            if ( !_elem.hasClass('hideGroup') ) {
                _elem.addClass('hideGroup').hide();
            }else{
                _elem.removeClass('hideGroup').show();
            }
        });

        return false;
    }

<?php $this->headScript()->captureEnd(); ?>
</script>