<ul class="contents">
    <li>
        <a href="javascript:window.history.back();">
            <img class="mb-3" src="/_images/icon/bullet_go_left.png"> <?php echo $this->translate('Back');?>
        </a>
    </li>
    <li>
        <a href="<?php echo $this->url(array('inquiry_channel' => ExhibStand::INQUIRY_CHANNEL), 'inquiry_admin_sort');?>">
            <img class="mb-3" src="/_images/icon/tango_16/edit-copy.png"> <?php echo $this->translate('nav_section-nav_inquiry_stand');?>
        </a>
    </li>
    <li>
        <a href="<?php echo $this->url(array('inquiry_channel' => StandProduct::INQUIRY_CHANNEL_PRODUCT), 'inquiry_admin_sort');?>">
            <img class="mb-3" src="/_images/icon/tango_16/edit-copy.png"> <?php echo $this->translate('nav_section-nav_inquiry_product');?>
        </a>
    </li>
</ul>
