<ul class="contents">

    <li>
        <a href="<?php echo $this->url(array(), 'event_admin-stand-view-image_new'); ?>">
            <img class="mb-3" src="/_images/icon/add.png"> <?php echo $this->translate('nav_section-nav_stand-view-image_add'); ?>
        </a>
    </li>

    <li style="margin-bottom: 18px;">
        <a href="<?php echo $this->url(array(), 'event_admin-stand-view-image'); ?>">
            <img class="mb-3" src="/_images/icon/tango_16/edit-copy.png"> <?php echo $this->translate('nav_section-nav_stand-view-image_list'); ?>
        </a>
    </li>

</ul>
