<?php $this->placeholder('headling_1')->captureStart(); ?>
<?php
echo $this->partial(
	'_headling_button.phtml', array('title' => $this->translate('Add new category'), 'url' => '/admin/slider-category/new'));
?>

<h1><?php echo $this->placeholder('headling_1_content'); ?></h1>
<?php $this->placeholder('headling_1')->captureEnd(); ?>

<?php $this->placeholder('aside')->captureStart(); ?>
<?php echo $this->filter; ?>
<script type="text/javascript">
    $(document).ready(function(){
	changeFilterSelect('select-slider-category-filter');
    });
    
</script>
<?php $this->placeholder('aside')->captureEnd(); ?>

<?php $this->placeholder('toolbar')->captureStart(); ?>
<?php echo $this->render('admin/pagination.phtml'); ?>
<?php $this->placeholder('toolbar')->captureEnd(); ?>

<form id="grid-action-form" method="post" action="">
    <div class="toolbar toolbar-top"><?php echo $this->placeholder('toolbar'); ?></div>
    <table cellspacing="0" cellpadding="0" class="grid datas">
        <tbody>
            <tr>
                <th width="10" class="head first"></th>
		<th class="head <?php if ($this->orderCol == 'title'): ?>sorting-<?php if ($this->orderDir == 'DESC'): ?>desc<?php else: ?>asc<?php endif; ?><?php endif; ?>">
                    <a href="?order=title <?php if ($this->orderDir == 'DESC'): ?>ASC<?php else: ?>DESC<?php endif; ?>&page=1">
                        <span class="ui-icon"></span><?php echo $this->translate('Title');?>
                    </a>
                </th>
                <th class="head <?php if ($this->orderCol == 'created_at'): ?>sorting-<?php if ($this->orderDir == 'DESC'): ?>desc<?php else: ?>asc<?php endif; ?><?php endif; ?>">
                    <a href="?order=created_at <?php if ($this->orderDir == 'DESC'): ?>ASC<?php else: ?>DESC<?php endif; ?>&page=1">
                        <span class="ui-icon"></span><?php echo $this->translate('Created');?>
                    </a>
                </th>
                <th class="head <?php if ($this->orderCol == 'is_active'): ?>sorting-<?php if ($this->orderDir == 'DESC'): ?>desc<?php else: ?>asc<?php endif; ?><?php endif; ?>">
                    <a href="?order=is_active <?php if ($this->orderDir == 'DESC'): ?>ASC<?php else: ?>DESC<?php endif; ?>&page=1">
                        <span class="ui-icon"></span><?php echo $this->translate('Is active');?>
                    </a>
                </th>
		<th width="60px" class="head"></th>
            </tr>
            <tr class="row row-template">
                <td valign="top" class="first col"></td>
                <td valign="top" class="col"></td>
                <td valign="top" class="col"></td>
                <td valign="top" class="col"></td>
                <td valign="top" class="col"></td>
            </tr>

	    <?php foreach ($this->sliderCategoryList as $key => $sliderCategory): ?>
    	    <tr class="row <?php if (0 == ($key % 2)): ?>odd<?php else: ?>even<?php endif; ?>">
    		<td valign="top" class="col"><input type="checkbox" name="rowId[]" value="1"></td>
    		<td valign="top" class="col">
    		    <a class="edit" href="<?php echo $this->url(array('hash' => $sliderCategory->getHash()), 'admin_slider'); ?>">
			    <?php echo $this->escape($sliderCategory->getTitle()); ?>
			    <?php if (false === $sliderCategory->languageExists($this->selectedLanguage)): ?>
				<a href="#" title="Brak tłumaczenia">[!]</a>
			    <?php endif; ?>
    		    </a>
    		</td>
    		<td valign="top" class="col"><?php echo date('Y-m-d H:i', strtotime($sliderCategory->created_at)); ?></td>
    		<td valign="top" class="col">
			<?php $isActive = (int) $sliderCategory->is_active; ?>
    		    <a href="<?php echo $this->url(array('hash' => $sliderCategory->getHash()), 'admin_slider-category_status'); ?>" class="status">
    			<span class="switch-<?php echo $isActive; ?>"><?php echo $isActive; ?></span>
    		    </a>
    		</td>
    		<td valign="top" class="col">
    		    <ul class="actions">
    			<li>
    			    <a title="Add" class="help" href="<?php echo $this->url(array('hash' => $sliderCategory->getHash()), 'admin_slider_new'); ?>">
    				<span class="ui-icon ui-icon-plus"><?php echo $this->translate('Add');?></span>
    				<span class="bullet" style="width: 24px;"><?php echo $this->translate('Add');?></span>
    				<span class="ui-icon ui-icon-triangle-1-s queue"></span>
    			    </a>
    			</li>
    			<li>
    			    <a title="Edit" class="help" href="<?php echo $this->url(array('hash' => $sliderCategory->getHash()), 'admin_slider-category_edit'); ?>">
    				<span class="ui-icon ui-icon-pencil"><?php echo $this->translate('Edit');?></span>
    				<span class="bullet" style="width: 24px;"><?php echo $this->translate('Edit');?></span>
    				<span class="ui-icon ui-icon-triangle-1-s queue"></span>
    			    </a>
    			</li>
    			<li>
    			    <a onclick="return confirm(<?php echo $this->translate('Are you sure you want to delete this item?')?>);" title="Delete" class="help" href="<?php echo $this->url(array('hash' => $sliderCategory->getHash()), 'admin_slider-category_delete'); ?>">
    				<span class="ui-icon ui-icon-close"><?php echo $this->translate('Delete')?></span>
    				<span class="bullet" style="width: 36px;"><?php echo $this->translate('Delete')?></span>
    				<span class="ui-icon ui-icon-triangle-1-s queue"></span>
    			    </a>
    			</li>
    		    </ul>
    		</td>
    	    </tr>
	    <?php endforeach; ?>

        </tbody>
    </table>
    <div class="toolbar toolbar-bottom"><?php echo $this->placeholder('toolbar'); ?></div>
</form>