<?php if ($this->baseUserLanguageList->count() > 1): ?>
    <div class="lang_module">
        <div>
    	<div class="active_lang">
    	    <?php echo $this->translate('cms_label_language'); ?>:
    	    <a href="javascript:void(0)">
		    <?php if ($this->selectedLanguage->issetIcon()): ?>
			<img src="<?php echo $this->selectedLanguage->getIconSrc(); ?>" />
		    <?php endif; ?>
		    <?php echo $this->escape($this->selectedLanguage->original_name); ?>
    	    </a>
    	</div>

    	<div class="lang_list" style="display:none;">
    	    <ul>
		    <?php foreach ($this->baseUserLanguageList as $language): ?>
			<li>
			    <a href="?setSelectedLanguage=<?= $language->code ?>" title="<?= $this->escape($language->name) ?>">
				<span>
				    <span>
					<?php if ($language->issetIcon()): ?>
	    				<img src="<?php echo $language->getIconSrc(); ?>" />
					<?php endif; ?>
				    </span>
				    <?= $this->escape($language->original_name) ?>
				</span>
			    </a>
			</li>
		    <?php endforeach; ?>
    	    </ul>
    	</div>
        </div>
    </div>
<script type="text/javascript">
    $(document).ready(function(){
	$('div.lang_module div.active_lang a').click(function(){
	    $('div.lang_module div.lang_list').css('display')=='none'?$('div.lang_module div.lang_list').css('display','block'):$('div.lang_module div.lang_list').css('display','none');
	});
    });
</script>
<?php endif; ?>