<?php $this->placeholder('headling_1')->captureStart(); ?>
<?php
echo $this->partial(
    '_headling_button.phtml', array('title' => $this->translate('cms_button_new-participation-'.$this->exhibParticipationType->type), 'url' => $this->url( array(), 'user_admin-participation_new-'.$this->exhibParticipationType->getId() ) ) );
?>
<h1><?php echo $this->placeholder('headling_1_content'); ?></h1>
<?php $this->placeholder('headling_1')->captureEnd(); ?>
    <?php $this->placeholder('toolbar')->captureStart(); ?>
    <?php echo $this->render('commponents/pagination.phtml'); ?>
<?php $this->placeholder('toolbar')->captureEnd(); ?>

<h2>
    <?php echo $this->translate('label_selected_menage_even'); ?>:
    <?php echo $this->escape($this->selectedEvent->getTitle()); ?>
</h2>

<form id="grid-action-form" method="post" action="">
    <div class="toolbar toolbar-top"><?php echo $this->placeholder('toolbar'); ?></div>
    <table cellspacing="0" cellpadding="0" class="grid datas">
        <tr>
            <th class="head">
                <?php echo $this->translate('label_user_admin-participation_list-user'); ?>
            </th>
            <th class="head">
                <?php echo $this->translate('label_user_admin-participation_list-email'); ?>
            </th>
            <th class="head">
                <?php echo $this->translate('label_user_admin-participation_list-is-active'); ?>
            </th>
            <th width="60px" class="head"></th>
        </tr>
        <tr class="row row-template">
            <td valign="top" class="col"></td>
            <td valign="top" class="col"></td>
            <td valign="top" class="col"></td>
            <td valign="top" class="col"></td>
        </tr>

        <?php foreach ($this->participationList as $key => $participation): ?>
            <tr class="row <?php if (0 == ($key % 2)): ?>odd<?php else: ?>even<?php endif; ?>">
                <td valign="top" class="col">
                    <?php echo $this->escape($participation->User->getName()); ?>
                </td>
                <td valign="top" class="col">
                    <?php echo $this->escape($participation->User->getEmail()); ?>
                </td>
                <td valign="top" class="col">
                    <?php $isActive = (int) $participation->is_active; ?>
                    <a href="<?php echo $this->url(array('exhib_participation_hash' => $participation->getHash()), 'user_admin-participation_status'); ?>" class="status">
                        <span class="switch-<?php echo $isActive; ?>"><?php echo $isActive; ?></span>
                    </a>
                </td>
                <td valign="top" class="col">
                    <ul class="actions">
                        <li>
                            <a onclick="return confirm('<?php echo $this->translate('Are you sure you want to delete this participation?'); ?>');" title="<?php echo $this->translate('Delete'); ?>" class="help" href="<?php echo $this->url(array('exhib_participation_hash' => $participation->getHash() ), 'user_admin-participation_delete');  ?>">
                                <span class="ui-icon ui-icon-close"><?php echo $this->translate('label_cms_delete'); ?></span>
                                <span class="bullet" style="width: 36px;"><?php echo $this->translate('label_cms_delete'); ?></span>
                                <span class="ui-icon ui-icon-triangle-1-s queue"></span>
                            </a>
                        </li>
                    </ul>
                </td>
            </tr>
        <?php endforeach; ?>

    </table>

</form>
<div class="toolbar toolbar-bottom"><?php echo $this->placeholder('toolbar'); ?></div>

