<div class="tabs">
    <?php $i = 0; ?>
    <?php foreach( $this->briefcaseList as  $key => $briefcase ): ?>
        <?php if(!empty($briefcase['view'])): ?>
            <a href="javascript:;" onclick="changeTab(this, <?php echo $key; ?>)" class="<?php if($i==0): ?>active<?php endif; ?>"><?php echo $this->translate($briefcase['briefcaseType']['name']) ?></a>
            <?php $i++; ?>
        <?php endif; ?>
    <?php endforeach; ?>
    <div class="clr"></div>
</div>
<h2><?php echo $this->escape( $this->translate('label_briefcase_index_index_briefcase') ); ?></h2>
<div class="clr"></div>


<div class="tabsCont">
    <?php if( count($this->briefcaseList) > 0 ): ?>
        <?php $i = 0; ?>
        <?php foreach( $this->briefcaseList as $key => $briefcase ): ?>
            <div class="tabCont <?php if($i==0): ?>active<?php endif; ?>" id="<?php echo $key;?>">
                <div class="dataTableRdk">
                    <?php if(!empty($briefcase['view'])): ?>
                        <div><?php echo $briefcase['view']; ?></div>
                    <?php endif ;?>
                </div>
            </div>
            <?php $i++; ?>
        <?php endforeach; ?>
    <?php else :?>
            <?php echo $this->translate( 'label_briefcase_index_index_briefcase-empty' ); ?>
    <?php endif; ?>
</div>
        

<?php $this->headScript()->captureStart(); ?>
    function changeTab(current, i) {
        $('.tabs a').removeClass('active');
        $(current).addClass('active');
        $('.tabsCont .tabCont').hide();
        $('#'+i).show();
        $('#'+i + ' .mCustomScrollbar').mCustomScrollbar('update');
    }
<?php $this->headScript()->captureEnd(); ?>