<h2>Regulamin</h2>
<ol class="rules_list">
	<li>Administratorem danych osobowych gromadzonych w związku z
		korzystaniem przez Korzystających z serwisu jest Loyal Solutions Sp. z o.o. z siedzibą w Opolu, ul. Budowlanych 52</li>

	<li>Udostępnione przez Korzystających dane osobowe zbierane są w celach
		marketingowych, informacyjnych, statystycznych, konkursowych a także w
		celu badania opinii publicznej.</li>

	<li>Wszystkie gromadzone dane osobowe udostępniane są przez
		Korzystających dobrowolnie.</li>

	<li>Udostępniając swoje dane osobowe, Korzystający mają prawo do ich
		kontroli, poprawiania oraz uaktualniania, a także usuwania.</li>

	<li>Korzystający zobowiązany jest do podania prawdziwych danych. W
		przypadku stwierdzenia, że dane nie są prawdziwe, Administrator ma
		prawo usunąć jego dane. Powyższe postanowienia nie wyłączają prawa
		Administratora do dochodzenia odszkodowania odpowiadającego wysokości
		poniesionej z tego tytułu szkody.</li>

	<li>Akceptując niniejszy Regulamin Użytkownik Targów IT Career Expo wyraża zgodę
		na przetwarzanie podanych danych zgodnie z Ustawą z dnia 29.08.1997
		roku o Ochronie Danych Osobowych (Dz. U. Nr. 133, poz. 833, z późn.
		zm.) oraz na otrzymywanie drogą elektroniczną informacji handlowych
		zgodnie z Ustawą o świadczeniu usług drogą elektroniczną z dnia
		18.07.2002 r. (Dz.U.02.144.1204).</li>

	<li>Użytkownik wyraża zgodę na przekazanie swoich danych osobowych
		firmom/wystawcom, którzy biorą udział w Targach IT Career Expo organizowanych
		przez IDG Poland na cele marketingowe, informacyjne,
		statystyczne a także w celu badania opinii publicznej.</li>
</ol>