<?php

/**
 * AuthResource.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     ##NAME## <##EMAIL##>
 *
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AuthResource extends Table_AuthResource
{
    /**
     * @param string $moduleName
     *
     * @return array resourceName=>parentName
     */
    public static function getResourcesForModule($moduleName = 'default')
    {
        $resources = [];
        $resources[$moduleName] = null;
        $module = Doctrine::getTable(__CLASS__)->findOneByName($moduleName);

        $controllers = Doctrine_Query::create()
            ->select('id_auth_resource, name')
            ->from('AuthResource')
            ->where('id_parent = ? ', [$module->id_auth_resource])
            ->execute()->toKeyValueArray('id_auth_resource', 'name');

        foreach ($controllers as $id => $controllerName) {
            $resources[$controllerName] = $moduleName;
            $actions = Doctrine_Query::create()
                ->select('id_auth_resource, name')
                ->from('AuthResource')
                ->where('id_parent = ? ', [$id])
                ->execute()->toKeyValueArray('id_auth_resource', 'name');
            foreach ($actions as $action) {
                $resources[$action] = $controllerName;
            }
        }

        return $resources;
    }
}
