<?php

/**
 * BriefcaseLink.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     ##NAME## <##EMAIL##>
 *
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BriefcaseLink extends Table_BriefcaseLink
{
    /**
     * @param $id
     * @param null $id_language
     * @param null $tableName
     * @return BriefcaseLink
     */
    public static function find($id, $id_language = null, $tableName = null)
    {
        return Doctrine::getTable('BriefcaseLink')->find($id);
    }

    public function getId()
    {
        return $this->id_briefcase_link;
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function getLink()
    {
        return $this->link;
    }

    public function setTitle($value)
    {
        $this->title = $value;

        return $this;
    }

    public function setLink($value)
    {
        $this->link = $value;

        return $this;
    }
}
