<?php

/**
 * Briefcase.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     ##NAME## <##EMAIL##>
 *
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Briefcase extends Table_Briefcase
{
    public function getId()
    {
        return $this->id_briefcase;
    }

    /**
     * @param User       $user
     * @param int        $id_briefcase_type
     * @param int        $id_element
     * @param null|mixed $id_namespace
     *
     * @return bool
     */
    public static function checkUserHasElement($user, $id_briefcase_type, $id_element, $id_namespace = null)
    {
        return (bool) self::getUserElement($user, $id_briefcase_type, $id_element, $id_namespace);
    }

    /**
     * @param User|int       $user
     * @param int        $id_briefcase_type
     * @param int        $id_element
     * @param null|mixed $id_namespace
     */
    public static function getUserElement($user, $id_briefcase_type, $id_element, $id_namespace = null)
    {
        $id_user = $user instanceof User ? $user->getId() : $user;

        $query = Doctrine_Query::create()
            ->from('Briefcase b')
            ->where(
                'b.id_user = ? AND b.id_briefcase_type = ? AND b.id_element = ?',
                [$id_user, $id_briefcase_type, $id_element]
            )
            ->limit(1)
        ;

        if (null !== $id_namespace) {
            $query->addWhere('b.id_namespace = ?', $id_namespace);
        }

        return $query->execute()->getFirst();
    }
}
