<?php

/**
 * BriefcaseType.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     ##NAME## <##EMAIL##>
 *
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BriefcaseType extends Table_BriefcaseType
{
    const TYPE_BRIEFCASE_LINK = 1;
    /**
     * Materiały z biura organizacyjnego.
     */
    const TYPE_BRIEFCASE_OFFICE = 2;
    /**
     * Materiały ze stoiska.
     */
    const TYPE_BRIEFCASE_DOCUMENT = 3;
    /**
     * Stoiska.
     */
    const TYPE_BRIEFCASE_STAND = 4;

    const TYPE_BRIEFCASE_ONE_TO_ONE_CONFRENECE = 5;
    /**
     * produkty ze stoiska.
     */
    const TYPE_BRIEFCASE_PRODUCT = 6;
    /**
     * sklep.
     */
    const TYPE_BRIEFCASE_SHOP = 7;

    /**
     * @param $id
     * @param null $id_language
     * @param null $tableName
     * @return BriefcaseType
     */
    public static function find($id, $id_language = null, $tableName = null)
    {
        return Doctrine::getTable('BriefcaseType')->find($id);
    }

    public static function findOneByIdAndIsActive($id_briefcase_type)
    {
        return Doctrine_Query::create()
            ->from('BriefcaseType')
            ->where('id_briefcase_type = ?', $id_briefcase_type)
            ->addWhere('is_active = 1')
            ->fetchOne()
        ;
    }

    public function getId()
    {
        return $this->id_briefcase_type;
    }

    public function getName()
    {
        return $this->name;
    }
}
