<?php

/**
 * EventHasUser.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     ##NAME## <##EMAIL##>
 *
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class EventHasUser extends Table_EventHasUser
{
    /**
     * @param string $field
     *
     * @return string
     */
    public function getHash()
    {
        return $this->getField('hash');
    }

    /**
     * @param string $field
     *
     * @return string
     */
    public function getField($field)
    {
        return $this->{$field};
    }

    /**
     * @param string $hash
     *
     * @return EventHasUser
     */
    public static function findOneByHash($hash)
    {
        return Doctrine::getTable('EventHasUser')->findOneByHash($hash);
    }

    public function isNew()
    {
        return null === $this->hash;
    }
}
