<?php

/**
 * EventBackground.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     ##NAME## <##EMAIL##>
 *
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class EventBackground extends Table_EventBackground
{
    public function getUri()
    {
        $code = Engine_I18n::getLangCode();
        $uri = pathinfo($this->uri);

        return CDN_DOMAIN . $uri['dirname'] . '/' . $uri['filename'] . '_' . $code . '.' . $uri['extension'];
    }
}
