<?php

/**
 * EventStandNumber.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     ##NAME## <##EMAIL##>
 *
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class EventStandNumber extends Table_EventStandNumber
{
    public static function findOneByIdAndEventHallMap($id, $id_event_hall_map)
    {
        return Doctrine_Query::create()
            ->from('EventStandNumber esn')
            ->where(
                'esn.id_event_stand_number = ? AND esn.id_event_hall_map = ?',
                [$id, $id_event_hall_map]
            )
            ->execute()
            ->getFirst()
        ;
    }
}
