<?php

/**
 * ExhibHall.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     ##NAME## <##EMAIL##>
 *
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ExhibHall extends Table_ExhibHall
{
    public function getHash()
    {
        return $this->hash;
    }

    public function getId()
    {
        return $this->id_exhib_hall;
    }

    public function getName()
    {
        return $this->name;
    }

    public function setName($value)
    {
        return $this->name = $value;
    }

    public static function findOneByHash($hash)
    {
        $query = Doctrine_Query::create()
            ->from('ExhibHall h')
            ->where('h.hash = ?', [$hash])
        ;

        return $query->execute()->getFirst();
    }
}
