<?php

/**
 * ExhibParticipationType.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     ##NAME## <##EMAIL##>
 *
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ExhibParticipationType extends Table_ExhibParticipationType
{
    /**
     * Organizator.
     */
    const TYPE_ORGANIZER = 1;
    /**
     * Wystawca.
     */
    const TYPE_EXHIBITOR = 2;
    /**
     * Prelegent.
     */
    const TYPE_SPEAKER = 3;
    /**
     * Sponsor bez stoiska.
     */
    const TYPE_SPONSOR_WITHOUT_STAND = 4;
    /**
     * Uczestnik.
     */
    const TYPE_PARTICIPANT = 5;
    /**
     * Moderator.
     */
    const TYPE_MODERATOR = 6;

    /**
     * @return ExhibParticipationType
     */
    public static function getParticipantType()
    {
        return self::find(self::TYPE_PARTICIPANT);
    }

    /**
     * @return ExhibParticipationType
     */
    public static function getExhibitorType()
    {
        return self::find(self::TYPE_EXHIBITOR);
    }

    /**
     * @return ExhibParticipationType
     */
    public static function getOrganizerType()
    {
        return self::find(self::TYPE_ORGANIZER);
    }

    /**
     * @return ExhibParticipationType
     */
    public static function getModeratorType()
    {
        return self::find(self::TYPE_MODERATOR);
    }

    /**
     * @param int $id_exhib_participation_type
     *
     * @return ExhibParticipationType
     */
    public static function find($id, $id_language = null, $tableName = null)
    {
        return Doctrine::getTable('ExhibParticipationType')->find($id);
    }

    public function getId()
    {
        return $this->id_exhib_participation_type;
    }
}
