<?php

/**
 * ExhibStandHasBrand.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     ##NAME## <##EMAIL##>
 *
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ExhibStandHasBrand extends Table_ExhibStandHasBrand
{
    public function getIdBrand()
    {
        return $this->id_brand;
    }
}
