<?php

/**
 * HomePage.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     ##NAME## <##EMAIL##>
 *
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class HomePage extends Table_HomePage
{
    private $_boxSponsorsData;

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id_home_page;
    }

    /**
     * @return array|mixed
     */
    public function getPageData()
    {
        return json_decode($this->Version->data, true);
    }

    /**
     * @param $data
     *
     * @return HomePage
     */
    public function setPageData($data)
    {
        $this->Version->data = json_encode($data);

        return $this;
    }

    /**
     * @param $id
     * @param $language Language
     *
     * @return HomePage
     */
    public static function find($id, $language = null, $tableName = null)
    {
        return Doctrine_Query::create()
            ->from('HomePage hp')
            ->innerJoin('hp.Version hpv')
            ->where(
                'hp.id_home_page = ? AND hpv.id_language = ?',
                [$id, $language->getId()]
            )
            ->limit(1)
            ->execute()
            ->getFirst()
        ;
    }

    public function hasEvent()
    {
        return isset($this->Event) ? true : false;
    }

    public function getHash()
    {
        return $this->hash;
    }
}
