<?php

/**
 * HomePageVersion.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     ##NAME## <##EMAIL##>
 *
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class HomePageVersion extends Table_HomePageVersion
{
    private $_boxSponsorsData;

    public function getId()
    {
        return $this->id_home_page;
    }

    public function getDataRaw()
    {
        return $this->data;
    }

    public function getIdLanguage()
    {
        return $this->id_language;
    }

    public function setData($data)
    {
        $this->data = $data;
    }

    /**
     * @return array|mixed
     */
    public function getPageData()
    {
        if (null === $this->_boxSponsorsData) {
            $this->_boxSponsorsData = @json_decode($this->data, true);
        }

        return $this->_boxSponsorsData;
    }

    /**
     * @param $data
     *
     * @return HomePage
     */
    public function setPageData($data)
    {
        $this->_boxSponsorsData = ['sponsors' => $data];
        $this->data = json_encode($this->_boxSponsorsData);

        return $this;
    }
}
