<?php

/**
 * Inquiry.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     ##NAME## <##EMAIL##>
 *
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Inquiry extends Table_Inquiry
{
    const IS_READED = 1;
    const IS_NOT_READED = 0;

    public function getId()
    {
        return $this->id_inquiry;
    }

    public function getHash()
    {
        return $this->hash;
    }

    public function getIdBaseUser()
    {
        return $this->id_base_user;
    }

    public function getIdExhibStand()
    {
        return $this->id_exhib_stand;
    }

    public function setIsReaded($value)
    {
        return $this->is_readed = $value;
    }

    public function getIsReaded()
    {
        return (bool) $this->is_readed;
    }

    public function getChannel()
    {
        return $this->channel;
    }

    public function getCreatedAt()
    {
        return $this->created_at;
    }

    public function setSubject($value)
    {
        return $this->subject = $value;
    }

    public function getSubject()
    {
        return $this->subject;
    }

    public function hasFile()
    {
        $file = InquiryFile::findOneByIdInquiry($this->getId());

        if (!$file) {
            return false;
        }

        return true;
    }

    public function getFile()
    {
        $file = InquiryFile::findOneByIdInquiry($this->getId());

        if (!$file) {
            return false;
        }

        return $file;
    }
}
