<?php

/**
 * Module.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     ##NAME## <##EMAIL##>
 *
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Module extends Table_Module
{
    /**
     * @param mixed $id
     *
     * @return Module
     */
    public static function find($id, $id_language = null, $tableName = null)
    {
        return Doctrine::getTable('Module')->find($id);
    }

    public function getId()
    {
        return $this->id_module;
    }
}
