<?php

/**
 * Newsletter.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     ##NAME## <##EMAIL##>
 *
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Newsletter extends Table_Newsletter
{
    /**
     * @param striong $hash
     *
     * @return Newsletter
     */
    public function findOneByHash($hash)
    {
        return Doctrine::getTable('Newsletter')->findOneByHash($hash);
    }

    /**
     * @return string
     */
    public function getId()
    {
        return $this->id_newsletter;
    }

    /**
     * @return string
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }
}
