<?php

/**
 * NotificationToUser.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     ##NAME## <##EMAIL##>
 *
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class NotificationToUser extends Table_NotificationToUser
{
    public function delete(Doctrine_Connection $conn = null)
    {
        $this->visible_in_history = false;

        $this->save();
    }
}
