<?php

/**
 * SendToFriend.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     ##NAME## <##EMAIL##>
 *
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SendToFriend extends Table_SendToFriend
{
    public function getIdUser()
    {
        return $this->id_user;
    }

    public function getEmail()
    {
        return $this->email;
    }

    public function getDate()
    {
        return $this->date;
    }

    public function setIdUser($value)
    {
        $this->id_user = $value;

        return $this;
    }

    public function setEmail($value)
    {
        $this->email = $value;

        return $this;
    }

    public function setDate($value)
    {
        $this->date = $value;

        return $this;
    }

    public static function findByEmail($email)
    {
        return Doctrine_Query::create()
            ->from('SendToFriend stf')
            ->where('stf.email = ?', $email)
            ->execute()
        ;
    }
}
