<?php

/**
 * Session.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     ##NAME## <##EMAIL##>
 *
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Session extends Table_Session
{
    /**
     * @param string     $id
     * @param null|mixed $id_language
     * @param null|mixed $tableName
     *
     * @return Session
     */
    public static function find($id, $id_language = null, $tableName = null)
    {
        return Doctrine::getTable('Session')->find($id);
    }
}
