<?php

/**
 * StandProductTranslation.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     ##NAME## <##EMAIL##>
 *
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class StandProductTranslation extends Table_StandProductTranslation
{
    /**
     * @param $id_news
     * @param $id_language
     * @param mixed $id_stand_product
     *
     * @return StandProductTranslation
     */
    public static function find($id, $id_language = null, $tableName = null)
    {
        return Doctrine_Query::create()
            ->from(__CLASS__)
            ->where('id_stand_product = ? AND id_language = ?', [$id, $id_language])
            ->limit(1)
            ->execute()
            ->getFirst();
    }
}
