<?php

/**
 * StandLevel.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     ##NAME## <##EMAIL##>
 *
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class StandLevel extends Table_StandLevel
{
    const STANDARD = 1;
    const VIP = 2;

    const LEVEL_STANDARD = 1;
    const LEVEL_REGIONAL = 2;
    const LEVEL_MAIN = 3;
    const LEVEL_DEVELOPER = 4;

    public function getId()
    {
        return $this->id_stand_level;
    }

    public function getName()
    {
        return $this->name;
    }

    /**
     * @param int $id_exhib_stand_level
     *
     * @return StandLevel
     */
    public static function findOneById($id_exhib_stand_level)
    {
        return Doctrine::getTable(__CLASS__)->findOneById($id_exhib_stand_level);
    }

    public static function getAll()
    {
        $query = Doctrine_Query::create()
            ->from('ExhibStandLevel esl')
            ->orderBy('esl.name')
        ;

        return $query->execute();
    }
}
