<?php

/**
 * UserRole.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     ##NAME## <##EMAIL##>
 *
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UserRole extends Table_UserRole
{
    /**
     * konto uzytkownika.
     */
    const ROLE_USER = 1;

    /**
     * konto admina.
     */
    const ROLE_ADMIN = 2;

    /**
     * konto wystawcy - targi.
     */
    const ROLE_EXHIBITOR = 5;
    /**
     * organizator eventu.
     */
    const ROLE_EVENT_ORGANIZER = 3;

    /**
     * konto organizatora targów.
     */
    const ROLE_ORGANIZER = 4;

    /**
     * konto moderatora targów.
     */
    const ROLE_MODERATOR = 6;

    /**
     * niezalogowany gość.
     */
    const ROLE_GUEST = 7;

    public function getId()
    {
        return $this->id_user_role;
    }

    public function getName()
    {
        return $this->name;
    }

    public function getRoleName()
    {
        return $this->role;
    }

    /**
     * @param string   $role
     * @param BaseUser $baseUser
     *
     * @return UserRole
     */
    public static function findOneByRoleAndBaseUser($role, $baseUser)
    {
        return Doctrine_Query::create()
            ->from('UserRole ur')
            ->where('ur.role = ?', $role)
            ->addWhere('(ur.id_base_user = ? OR ur.id_base_user IS NULL)', $baseUser->getId())
            ->limit(1)
            ->execute()
            ->getFirst()
        ;
    }
}
