<?php

/**
 * UserConfirmRequest.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     ##NAME## <##EMAIL##>
 *
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UserConfirmRequest extends Table_UserConfirmRequest
{
    const ACCOUNT_ACTIVATION = 1;
    const EMAIL_ACTIVATION = 2;
    const CHANGE_PASSWORD = 3;

    public function getId()
    {
        return $this->id_confirm_request;
    }

    public function getUserId()
    {
        return $this->id_user;
    }

    public function getCreatedAt()
    {
        return $this->created_at;
    }

    public function setIsUsed($value)
    {
        return $this->is_used = $value;
    }

    public function getIsUsed()
    {
        return $this->is_used;
    }

    public function setUsedAt($value)
    {
        return $this->used_at = $value;
    }

    public function getUsedAt()
    {
        return $this->used_at;
    }

    public function getHash()
    {
        return $this->hash;
    }

    public function setType($value)
    {
        return $this->type = $value;
    }

    public function getType()
    {
        return $this->type;
    }

    /**
     * @param string $hash
     *
     * @return UserConfirmRequest
     */
    public function findOneByHash($hash)
    {
        return Doctrine::getTable(__CLASS__)->findOneByHash($hash);
    }

    /**
     * @param string $hash
     * @param string $type
     *
     * @return UserConfirmRequest
     */
    public static function findOneByHashAndType($hash, $type)
    {
        return Doctrine::getTable(__CLASS__)->findOneByHashAndType($hash, $type);
    }
}
