<?php $this->placeholder('headling_1')->captureStart(); ?>
    <?php
        echo $this->partial(
                '_headling_button.phtml',
                array(
                    'title' => $this->translate('label_cms_add-new-hallmap'),
                    'url' => $this->url(
                        array(),
                        'event_admin-hallmap_new'
                        )
                    )
                );
    ?>

    <h1><?php echo $this->placeholder('headling_1_content'); ?></h1>
<?php $this->placeholder('headling_1')->captureEnd(); ?>

<?php $this->placeholder('toolbar')->captureStart(); ?>
<?php echo $this->render('commponents/pagination.phtml'); ?>
<?php $this->placeholder('toolbar')->captureEnd(); ?>

<form id="grid-action-form" method="post" action="">
    <div class="toolbar toolbar-top"><?php echo $this->placeholder('toolbar'); ?></div>
    <table cellspacing="0" cellpadding="0" class="grid datas">
        <tbody>
            <tr>
                <th class="head first"><?=$this->translate('label_admin-hallmap-list_name');?></th>
                <th class="head"><?=$this->translate('label_admin-hallmap-list_event-name');?></th>
                <th class="head"><?=$this->translate('label_admin-hallmap-list_image-size');?></th>
                <th class="head"><?=$this->translate('label_admin-hallmap-list_numbers-count');?></th>
                <th class="head"></th>
            </tr>
            <tr class="row row-template">
                <td valign="top" class="first col"></td>
                <td valign="top" class="col"></td>
            </tr>

            <?php foreach ($this->eventHallMapsList as $key => $hallMap): ?>
                <tr class="row <?php if (0 == ($key % 2)): ?>odd<?php else: ?>even<?php endif; ?>">
                    <td valign="top" class="col">
                        <a class="edit" href="<?php echo $this->url(array('hallmap_hash' => $hallMap->getHash()), 'event_admin-hallmap_edit');?>">
                            <?=$this->escape($hallMap->getName())?>
                        </a>
                    </td>
                    <td valign="top" class="col">
                        <?php if($hallMap->Event): ?>
                            <a class="edit" href="<?php echo $this->url(array('hallmap_hash' => $hallMap->getHash()), 'event_admin-hallmap_edit');?>">
                                <?=$this->escape($hallMap->Event->getTitle())?>
                            </a>
                        <?php endif; ?>
                    </td>

                    <td class="row"><?=$hallMap->width?>x<?=$hallMap->height?></td>
                    <td class="row"><?=$hallMap->EventStandNumbers->count()?></td>

                    <td valign="top" class="col" nowrap>
                        <ul class="actions">
                            <li>
                                <a title="<?php echo $this->translate('Edit'); ?>" class="help" href="<?php echo $this->url(array('hallmap_hash' => $hallMap->getHash()), 'event_admin-hallmap_edit');?>">
                                    <span class="ui-icon ui-icon-pencil"><?php echo $this->translate('Edit'); ?></span>
                                    <span class="bullet" style="width: 24px;"><?php echo $this->translate('Edit'); ?></span>
                                    <span class="ui-icon ui-icon-triangle-1-s queue"></span>
                                </a>
                            </li>
                            <li>
                                <?php if (!$hallMap->hasEvent()): ?>
                                    <a onclick="return confirm('<?php echo $this->translate('Are you sure you want to delete this item?'); ?>');" title="<?php echo $this->translate('Delete'); ?>" class="help" href="<?php echo $this->url(array('hallmap_hash' => $hallMap->getHash()), 'event_admin-hallmap_delete');?>">
                                        <span class="ui-icon ui-icon-close"><?php echo $this->translate('Delete'); ?></span>
                                        <span class="bullet" style="width: 36px;"><?php echo $this->translate('Delete'); ?></span>
                                        <span class="ui-icon ui-icon-triangle-1-s queue"></span>
                                    </a>
                                <?php endif; ?>
                            </li>
                        </ul>
                    </td>
                </tr>                
            <?php endforeach; ?>

        </tbody>
    </table>

</form>
<div class="toolbar toolbar-bottom"><?php echo $this->placeholder('toolbar'); ?></div>