<ul class="contents">
    <li>
    <a href="javascript:window.history.back();">       
        <img class="mb-3" src="/_images/icon/bullet_go_left.png"><?php echo $this->translate('Back');?>
    </a>
</li>
  <li>
        <a href="<?php echo $this->url( array(), 'company_admin' ); ?>">Pokaż listę firm</a>
    </li> 
    <li>
        <a href="<?php echo $this->url( array(), 'company_admin-user' ); ?>">Pokaż listę zatrudnienia</a>
    </li>
    <li>
        <a href="<?php echo $this->url( array(), 'company_admin-user_new' ); ?>">Dodaj zatrudnienie</a>
    </li>
  
    
</ul>