
<!DOCTYPE html>
<html lang="en">
    <head>
	 <meta charset="utf-8">
    <title>Messages</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="noindex">
    <link href="/_css/admin/bootstrap.css" media="screen" rel="stylesheet" type="text/css" />
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>


        <div style="padding:50px 0;">
        <div class="alert alert-success">
            <p><i class="icon-info-sign"></i> <?php echo $this->message; ?></p>
        </div>
        </div>

    <script type="text/javascript" src="/_js/admin/bootstrap.js"></script>
</body>
</html>
