<?php if( isset( $this->event ) && !$this->event->isNew() ): ?>
    <div class="spacerL"></div>
    <ul class="contents">
        <li>
            <a href="<?php echo $this->url( array( 'hash' => $this->event->getHash() ), 'admin_event_edit' ); ?>">
                <img class="mb-3" src="/_images/icon/bullet_go.png"> <?php echo $this->translate('nav_section-nav_event-edit'); ?>
            </a>
        </li>
        <!-- <li>
            <a href="<?php //echo $this->url( array( 'hash' => $this->event->getHash() ), 'event_admin-plan' ); ?>">
                <img class="mb-3" src="/_images/icon/date.png"> <?php //echo $this->translate('nav_section-nav_event_show-plan'); ?>
            </a>
        </li> -->
        <li>
            <a href="<?php echo $this->url( array( 'hash' => $this->event->getHash() ), 'event_admin-file' ); ?>">
               <img class="mb-3" src="/_images/icon/tango_16/edit-copy.png"> <?php echo $this->translate('nav_section-nav_event_files'); ?>
            </a>
        </li>
        <li>
            <a href="<?php echo $this->url( array( 'hash' => $this->event->getHash() ), 'event_admin-site' ); ?>">
               <img class="mb-3" src="/_images/icon/tango_16/edit-copy.png"> <?php echo $this->translate('nav_section-nav_event_sites'); ?>
            </a>
        </li>
    </ul>
<?php endif; ?>