<?php if($this->exhib_stand && !$this->exhib_stand->isNew() ): ?>
    <div class="spacerL"></div>
    <ul class="contents">
        <li>
            <a href="<?php echo $this->url(array('stand_hash' => $this->exhib_stand->getHash()), 'event_admin-stand_edit'); ?>">
                <img class="mb-3" src="/_images/icon/bullet_go.png"><?php echo $this->translate('Show stand'); ?>
            </a>
        </li>
        <li>
            <a href="<?php echo $this->url( array( 'hash' => $this->exhib_stand->getHash(), 'event_hash' => $this->selected_event_hash ), 'event_admin-stand-files_new' ); ?>">
               <img class="mb-3" src="/_images/icon/ico1/add-page-yellow.gif"> <?php echo $this->translate('Add new file'); ?>
            </a>
        </li>
        <li>
            <a href="<?php echo $this->url( array( 'hash' => $this->exhib_stand->getHash(), 'event_hash' => $this->selected_event_hash ), 'event_admin-stand-files_index' ); ?>">
               <img class="mb-3" src="/_images/icon/tango_16/edit-copy.png"> <?php echo $this->translate('File list'); ?>
            </a>
        </li>
        <li>
            <a href="<?php echo $this->url( array( 'stand_hash' => $this->exhib_stand->getHash()), 'event_admin-stand-offer_index' ); ?>">
               <img class="mb-3" src="/_images/icon/tango_16/edit-copy.png"> <?php echo $this->translate('nav_section-nav_offer-list'); ?>
            </a>
        </li>
        <li>
            <a href="<?php echo $this->url( array( 'stand_hash' => $this->exhib_stand->getHash()), 'admin_stand-video_index' ); ?>">
               <img class="mb-3" src="/_images/icon/tango_16/edit-copy.png"> <?php echo $this->translate('nav_section-nav_video-list'); ?>
            </a>
        </li>
    </ul>
<?php endif; ?>
<?php echo $this->render('admin/_contentNav.phtml'); ?>
