<?php $this->placeholder('headling_1')->captureStart(); ?>
    <?php
    echo $this->partial(
        '_headling_button.phtml', array('title' => $this->translate('Add new file'), 'url' => $this->url( array( 'hash' => $this->exhib_stand->getHash(), 'event_hash' => $this->selected_event_hash ), 'event_admin-stand-files_new')));
    ?>
    <h1><?php echo $this->placeholder('headling_1_content'); ?></h1>
<?php $this->placeholder('headling_1')->captureEnd(); ?>



<div>
    <table class="grid datas">
        <tr>
            <td style="width: 25%"><b><?php echo $this->translate('Stand'); ?>: </b></td>
            <td><?php echo $this->escape( $this->exhib_stand->getName() ); ?></td>
        </tr>
    </table>
</div>
<div class="spacerL"></div>


<?php $this->placeholder('toolbar')->captureStart(); ?>
<?php echo $this->render('commponents/pagination.phtml'); ?>
<?php $this->placeholder('toolbar')->captureEnd(); ?>

<table cellspacing="0" cellpadding="0" class="grid datas">
    <tbody>
        <tr>
            <th class="head"><?php echo $this->translate('Name'); ?></th>
            <th class="head"><?php echo $this->translate('Link'); ?></th>
            <th class="head"><?php echo $this->translate('Options'); ?></th>
            <th class="head"><?php echo $this->translate('Is published?'); ?></th>
        </tr>
        <tr class="row row-template">
            <td valign="top" class="first col"></td>
            <td valign="top" class="col"></td>
            <td valign="top" class="col"></td>
            <td valign="top" class="col"></td>
        </tr>

        <?php if( $this->standFileList->count() === 0 ): ?>
            <tr>
                <td colspan="4">
                    <div class="msg-attention">
                            <?php echo $this->translate( 'The list is empty. If you want to add a new item' ); ?>
                            <a href="<?php echo $this->url( array( 'hash' => $this->exhib_stand->getHash(), 'event_hash' => $this->selected_event_hash ), 'event_admin-stand-files_new' ); ?>">
                                <?php echo $this->translate('click here'); ?> &raquo;
                            </a>
                    </div>
                </td>
            </tr>
        <?php else: ?>
             <?php foreach ($this->standFileList as $key => $standFile ): ?>
                <tr class="row <?php if (0 == ($key % 2)): ?>odd<?php else: ?>even<?php endif; ?>">
                    <td valign="top" class="col">
                        <a class="edit" href="<?php echo $this->url(array( 'hash' => $standFile->getHash(), 'event_hash' => $this->selected_event_hash), 'event_admin-stand-files_edit'); ?>">
                            <?php echo $this->escape( $standFile->getName() ); ?>
                        </a>
                    </td>
                    <td valign="top" class="col">
                        <a href="<?php echo $this->url(array( 'hash' => $standFile->getHash(), 'event_hash' => $this->selected_event_hash), 'event_admin-stand-files_download'); ?>" target="_blank">
                            <?php echo $this->translate('download_file');?> &raquo;
                        </a>
                    </td>
                    <td valign="top" class="col">
                        <ul class="actions">
                            <li>
                                <a title="<?php echo $this->translate('Edit'); ?>" class="help" href="<?php echo $this->url(array('hash' => $standFile->getHash(), 'event_hash' => $this->selected_event_hash), 'event_admin-stand-files_edit'); ?>">
                                    <span class="ui-icon ui-icon-pencil"><?php echo $this->translate('Edit'); ?></span>
                                    <span class="bullet" style="width: 24px;"><?php echo $this->translate('Edit'); ?></span>
                                    <span class="ui-icon ui-icon-triangle-1-s queue"></span>
                                </a>
                            </li>
                            <li>
                                <a onclick="return confirm('<?php echo $this->translate('Are you sure you want to delete this item?'); ?>');" title="<?php echo $this->translate('Delete'); ?>" class="help" href="<?php echo $this->url(array('hash' => $standFile->getHash(), 'event_hash' => $this->selected_event_hash), 'event_admin-stand-files_delete'); ?>">
                                    <span class="ui-icon ui-icon-close"><?php echo $this->translate('Delete'); ?></span>
                                    <span class="bullet" style="width: 36px;"><?php echo $this->translate('Delete'); ?></span>
                                    <span class="ui-icon ui-icon-triangle-1-s queue"></span>
                                </a>
                            </li>
                        </ul>
                    </td>
                    <td valign="top" class="col">
                        <?php if($standFile->is_published):?>
                            <?php echo $this->translate('Yes');?>
                        <?php else:?>
                            <?php echo $this->translate('No');?>
                        <?php endif;?>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>

    </tbody>
</table>
<div class="toolbar toolbar-bottom"><?php echo $this->placeholder('toolbar'); ?></div>