<table border="0" cellpadding="5" cellspacing="5" width="600"  style="font-size: 12px; font-family: Tahoma;">
    <tr>
        <th align="left"><b><?php echo $this->translate('label_user_account_send-to-friend-email_hello');?>, <?php echo $this->name; ?></b></th>
    </tr>
    <tr>
        <td>
            <?php echo $this->message; ?>
        </td>
    </tr>
    <tr>
        <td>
            <?php //echo $this->baseUser->getName();?>
        </td>
    </tr>
</table>
