<div class="frontend_content boxWithShadow">
    <?php $this->placeholder('h1')->captureStart(); ?>
    <h1><?php echo $this->escape( $this->translate('label_user_register_thx_change-pass') ); ?></h1>
    <?php $this->placeholder('h1')->captureEnd(); ?>
    <div class="thanks"><strong><?php echo $this->translate('label_user_register_thx_comm_change-pass') ;?></strong>.</div>
</div>
<div class="onlyShadow"></div>