<?php $this->placeholder('headling_1')->captureStart(); ?>
<?php echo $this->partial(
    '_headling_button.phtml', array('title' => $this->translate( 'Add Shop Location' ),
                                    'url' => $this->url(array(), 'shop_admin-location_new')));
?>
<h1><?php echo $this->placeholder('headling_1_content'); ?></h1>
<?php $this->placeholder('headling_1')->captureEnd(); ?>


<?php //$this->placeholder('toolbar')->captureStart(); ?>
<?php //echo $this->render('admin/pagination.phtml'); ?>
<?php //$this->placeholder('toolbar')->captureEnd(); ?>

<form id="grid-action-form" method="post" action="">
    <div class="toolbar toolbar-top"><?php echo $this->placeholder('toolbar'); ?></div>
    <table cellspacing="0" cellpadding="0" class="grid datas">
        <tbody>
        <tr>
            <th class="head first">
                <?php echo $this->translate('Lp.'); ?>
            </th>
            <th class="head">
                <?php echo $this->translate('Event'); ?>
            </th>
            <th class="head">
                <?php echo $this->translate('label_admin-location_shop_list_country'); ?>
            </th>
            <th class="head">
                <?php echo $this->translate('label_admin-location_shop_list_city'); ?>
            </th>
            <th class="head">
                <?php echo $this->translate('label_admin-location_shop_list_street'); ?>
            </th>
            <th class="head">
                <?php echo $this->translate('label_admin-location_shop_list_email'); ?>
            </th>
            <th width="60px" class="head"></th>
        </tr>
        <tr class="row row-template">
            <td valign="top" class="first col"></td>
            <td valign="top" class="col"></td>
            <td valign="top" class="col"></td>
            <td valign="top" class="col"></td>
            <td valign="top" class="col"></td>
            <td valign="top" class="col"></td>
            <td valign="top" class="col"></td>
        </tr>

        <?php foreach( $this->shopLocationList as $key => $shopLocation ): /** @var $shopLocation ShopLocation */ ?>
            <tr class="row <?php if( 0 == ($key%2) ): ?>odd<?php else: ?>even<?php endif; ?>">
                <td valign="top" class="col">
                    <?php echo ++$key.'.'; ?>
                </td>
                <td valign="top" class="col">
                    <?php echo $shopLocation->Event->getTitle(); ?>
                </td>
                <td valign="top" class="col">
                    <?php echo $shopLocation->getCountry() ?>
                </td>
                <td valign="top" class="col">
                    <?php echo $shopLocation->getCity() ?>
                </td>
                <td valign="top" class="col">
                    <?php echo $shopLocation->getStreet() ?>
                </td>
                <td valign="top" class="col">
                    <?php echo $shopLocation->getEmail(); ?>
                </td>
                <td valign="top" class="col">
                    <ul class="actions">
                        <li>
                            <a title="<?php echo $this->escape( $this->translate('Edit') ); ?>" class="help" href="<?php echo $this->url( array( 'hash' => $shopLocation->hash ), 'shop_admin-location_edit' ); ?>">
                                <span class="ui-icon ui-icon-pencil"><?php echo $this->escape( $this->translate('Edit') ); ?></span>
                                <span class="bullet" style="width: 36px;"><?php echo $this->escape( $this->translate('Edit') ); ?></span>
                                <span class="ui-icon ui-icon-triangle-1-s queue"></span>
                            </a>
                            <a onclick="return confirm('<?php echo $this->translate('Are you sure you want to delete this item?'); ?>');" title="<?php echo $this->escape( $this->translate('Delete') ); ?>" class="help" href="<?php echo $this->url( array( 'hash' => $shopLocation->hash ), 'shop_admin-location_delete' ); ?>">
                                <span class="ui-icon ui-icon-close"><?php echo $this->escape( $this->translate('Delete') ); ?></span>
                                <span class="bullet" style="width: 36px;"><?php echo $this->escape( $this->translate('Delete') ); ?></span>
                                <span class="ui-icon ui-icon-triangle-1-s queue"></span>
                            </a>
                        </li>
                    </ul>
                </td>
            </tr>
        <?php endforeach; ?>

        </tbody>
    </table>
    <div class="toolbar toolbar-bottom"><?php echo $this->placeholder('toolbar'); ?></div>
</form>