<?php
    $this->headLink()->appendStylesheet('/_css/admin/form.css');
    $this->headLink()->appendStylesheet('/_css/admin/ui.multiselect.css');
    $this->headLink()->appendStylesheet('/_css/admin/common.css');
    $this->headScript()->appendFile('/_js/admin/jquery-ui.min.js');
    $this->headScript()->appendFile('/_js/admin/ui.multiselect.js');
    $this->headScript()->appendFile('/_js/admin/all.js');
?>

<?php $this->placeholder('headling_1')->captureStart(); ?>
    <h1><?php echo $this->placeholder('headling_1_content'); ?></h1>
<?php $this->placeholder('headling_1')->captureEnd(); ?>

<?php echo $this->newsForm;?>

 <script>
    <?php $this->headScript()->captureStart(); ?>
        var select = $('.onHomePage'),
            parent = select.parent();
            parent.click(function() {
                if ( select.val() == '1') {
                    $('.image_home_class').show();
                }else{
                    $('.image_home_class').hide();
                }
            });
    <?php $this->headScript()->captureEnd(); ?>
</script>