<?php $this->placeholder('headling_1')->captureStart(); ?>
    <?php
    echo $this->partial(
        '_headling_button.phtml', array('title' => $this->translate( 'Add news' ), 'url' => $this->url(array(), 'news_admin_new')));
    ?>

    <h1><?php echo $this->placeholder('headling_1_content'); ?></h1>
<?php $this->placeholder('headling_1')->captureEnd(); ?>


<?php $this->placeholder('aside')->captureStart(); ?>
    <?php echo $this->filter; ?>
<?php $this->placeholder('aside')->captureEnd(); ?>

<script type="text/javascript">
//    $(document).ready(function(){
//        changeFilterSelect('select-filter');
//    });
</script>


<?php $this->placeholder('toolbar')->captureStart(); ?>
    <?php echo $this->render('admin/pagination.phtml'); ?>
<?php $this->placeholder('toolbar')->captureEnd(); ?>

<form id="grid-action-form" method="post" action="">
    <div class="toolbar toolbar-top"><?php echo $this->placeholder('toolbar'); ?></div>
    <table cellspacing="0" cellpadding="0" class="grid datas">
        <tbody>
            <tr>
                <th class="head first <?php if( $this->orderCol == 'created_at' ): ?>sorting-<?php if( $this->orderDir == 'DESC' ): ?>desc<?php else:?>asc<?php endif; ?><?php endif; ?>">
                    <a href="?order=created_at <?php if( $this->orderDir == 'DESC' ): ?>ASC<?php else: ?>DESC<?php endif; ?>&page=1">
                        <span class="ui-icon"></span>
                        <?php echo $this->translate('Created at'); ?>
                        
                    </a>
                </th>
                <th class="head <?php if( $this->orderCol == 'title' ): ?>sorting-<?php if( $this->orderDir == 'DESC' ): ?>desc<?php else:?>asc<?php endif; ?><?php endif; ?>">
                    <a href="?order=title <?php if( $this->orderDir == 'DESC' ): ?>ASC<?php else: ?>DESC<?php endif; ?>&page=1">
                        <span class="ui-icon"></span>
                        <?php echo $this->translate('Title'); ?>
                    </a>
                </th>
                <th class="head <?php if( $this->orderCol == 'is_active' ): ?>sorting-<?php if( $this->orderDir == 'DESC' ): ?>desc<?php else:?>asc<?php endif; ?><?php endif; ?>">
                    <a href="?order=is_active <?php if( $this->orderDir == 'DESC' ): ?>ASC<?php else: ?>DESC<?php endif; ?>&page=1">
                        <span class="ui-icon"></span>
                        <?php echo $this->translate('Visible'); ?>
                    </a>
                </th>
                <th width="60px" class="head"></th>
            </tr>
            <tr class="row row-template">
                <td valign="top" class="first col"></td>
                <td valign="top" class="col"></td>
                <td valign="top" class="col"></td>
                <td valign="top" class="col"></td>
            </tr>

            <?php foreach( $this->newsList as $key => $news ): ?>
                <tr class="row <?php if( 0 == ($key%2) ): ?>odd<?php else: ?>even<?php endif; ?>">
                    <td valign="top" class="col"><?php echo date( 'Y-m-d H:i', strtotime( $news->created_at ) ); ?></td>
                    <td valign="top" class="col">
                        <a class="edit" href="<?php echo $this->url( array( 'hash' => $news->hash ), 'news_admin_edit' ); ?>">
                            <?php echo $this->escape( $news->getTitle() ); ?>
                            <?php if(false === $news->translationExists()): ?>
                                <a href="#" title="<?=$this->translate('label_translation_not_exists')?>">[!]</a>
                            <?php endif; ?>
                        </a>
                        
                    </td>
                    <td valign="top" class="col">
                        <?php $isActive = (int)$news->is_active; ?>
                        <a href="<?php echo $this->url( array( 'hash' => $news->hash ), 'news_admin_status' ); ?>" class="status">
                            <span class="switch-<?php echo $isActive; ?>"><?php echo $isActive; ?></span>
                        </a>
                    </td>
                    <td valign="top" class="col">
                        <ul class="actions">
                            <li>
                                <a title="<?php echo $this->escape( $this->translate('Edit') ); ?>" class="help" href="<?php echo $this->url( array( 'hash' => $news->hash ), 'news_admin_edit' ); ?>">
                                    <span class="ui-icon ui-icon-pencil"><?php echo $this->escape( $this->translate('Edit') ); ?></span>
                                    <span class="bullet" style="width: 24px;"><?php echo $this->escape( $this->translate('Edit') ); ?></span>
                                    <span class="ui-icon ui-icon-triangle-1-s queue"></span>
                                </a>
                            </li>
                            <li>
                                <a onclick="return confirm('<?php echo $this->translate('Are you sure you want to delete this item?'); ?>');" title="<?php echo $this->escape( $this->translate('Delete') ); ?>" class="help" href="<?php echo $this->url( array( 'hash' => $news->hash ), 'news_admin_delete' ); ?>">
                                    <span class="ui-icon ui-icon-close"><?php echo $this->escape( $this->translate('Delete') ); ?></span>
                                    <span class="bullet" style="width: 36px;"><?php echo $this->escape( $this->translate('Delete') ); ?></span>
                                    <span class="ui-icon ui-icon-triangle-1-s queue"></span>
                                </a>
                            </li>
                        </ul>
                    </td>
                </tr>
            <?php endforeach; ?>

        </tbody>
    </table>
    <div class="toolbar toolbar-bottom"><?php echo $this->placeholder('toolbar'); ?></div>
</form>
