<div class="spacerM add_bborder"></div>
<div class="spacerM"></div>

<?php if($this->path != '' && $this->path != '/'):?>
	<div class="file_container">
		<div class="fileIconBig">
			<a href="<?=$this->url()?>?path=<?=$this->dirUp?>">
				<img src="/_images/icon/file_types/undo.png" />
			</a>
		</div>
		<div class="file_name">
			<a href="<?=$this->url()?>?path=<?=$this->dirUp?>">
				<span><i>..[<?php echo $this->translate('to up'); ?>]</i></span>
			</a>
		</div>
	</div>
<?php endif; ?>

<?php $i=0; ?>
<?php foreach($this->catalogContent as $element):?>
	<div id="elementList_<?=$i?>" class="file_container <?php if( $this->selectedFiles['files_path'] == $this->path && array_key_exists($element['file'], $this->selectedFiles['files']) ): ?><?=$this->selectedFiles['operation']?>File<?php endif; ?>">
		<div class="fileIconBig">
			<?php if($element['type']=='dir'):?>
				<a href="<?=$this->url()?>?path=<?=$this->path.'/'.$element['file']?>" onClick="return false;">
			<?php else: ?>
				<?php if( $this->mode == 'get' ): ?>
					<a href="#" getElement="<?=$this->browserPath.'/'.$element['file']?>" title="<?php echo $element['file']; ?>" onClick="return false;">
				<?php else: ?>
					<a href="<?=$this->browserPath.'/'.$element['file']?>?ts=<?=time()?>" onClick="return false;">
				<?php endif; ?>
			<?php endif; ?>
				<?php if( $element['is_image']): ?>
					<img src="<?=$this->browserPath?>/<?=$element['file']?>?ts=<?=time()?>" />
				<?php else: ?>
                    <?php if( file_exists( APPLICATION_WEB.DS.'_images/icon/file_types/'.$element['ext'].'.png' ) ): ?>
                        <img src="/_images/icon/file_types/<?=$element['ext']?>.png" />
                    <?php else: ?>
                        <img src="/_images/icon/file_types/file.png" />
                    <?php endif; ?>
				<?php endif; ?>
			</a>
		</div>
		
		<div class="file_name">
			<?php if($element['type']=='dir'):?>
				<a href="<?=$this->url()?>?path=<?=$this->path.'/'.$element['file']?>" onClick="return false;">
					<span><?=$element['file']?></span>
				</a>
			<?php else: ?>
				<?php if( $this->mode == 'get' ): ?>
					<a href="#" getElement="<?=$this->browserPath.'/'.$element['file']?>" title="<?php echo $element['file']; ?>" onClick="return false;">
				<?php else: ?>
					<a href="<?=$this->browserPath.'/'.$element['file']?>?ts=<?=time()?>" onClick="return false;">
				<?php endif; ?>
					<span><?=$element['file']?></span>
				</a>
			<?php endif; ?>
		</div>
		<div class="checkbox" style="position: relative;">
			<?=$this->formCheckbox('file['.$element['file'].']', 1, array( 'class' => 'selectedFile', 'idElementList' => 'elementList_'.$i, 'checked' => ( $this->selectedFiles['files_path'] == $this->path && array_key_exists($element['file'], $this->selectedFiles['files']) ) ) )?>
		</div>
		<?=$this->partial( 'admin/file_options.phtml', array( 'element' => $element, 'path' => $this->path, 'browserPath' => $this->browserPath, 'mode' => $this->mode, 't' => $this->t ) )?>
	</div>
	<?php $i++; ?>
<?php endforeach; ?>

<div class="cl"></div>
<div class="spacerM"></div>
<div class="spacerM add_tborder"></div>
