<ul class="contents">
    <li>
        <a href="<?php echo $this->url( array(), 'text_admin' ); ?>">
            <img src="/_images/icon/tango_16/edit-copy.png" class="mb-3">
            <?php echo $this->translate('nav_section-nav_text-list'); ?>
        </a>
    </li>
    <li>
        <a href="<?php echo $this->url( array(), 'text_admin_new' ); ?>">
            <img src="/_images/icon/add.png" class="mb-3">
            <?php echo $this->translate('nav_section-nav_text-new'); ?>
        </a>
    </li>
</ul>
